-- Seed 29 soal contoh resmi JLPT N5 (Mode 1) ke tabel
-- jlpt_exam_questions, hasil transkripsi dari data/jlpt-n5-tp1-data.js.
-- Jalankan SEKALI di Supabase SQL Editor SETELAH add-jlpt-exam-questions.sql.
-- Aman dijalankan ulang.

delete from public.jlpt_exam_questions where exam_id = 'n5-tp1' and mode = 'sample';

insert into public.jlpt_exam_questions (
  exam_id, mode, section, subcategory, question_number, question_type,
  instruction, question_html, options, correct_answer, explanation,
  reading_passage_id, image_url, audio_url, audio_start, audio_end,
  source_file, source_page, difficulty, status, position
) values
  ('n5-tp1', 'sample', 'vocabulary', 'kanji_reading', 1, 'MULTIPLE_CHOICE', '＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。', '<u>新しい</u> くるまですね。', '["あたらしい","あだらしい","あらたしい","あらだしい"]'::jsonb, 0, null, null, null, null, null, null, 'N5-mondai.pdf', 100, 'N5', 'official_sample', 1),
  ('n5-tp1', 'sample', 'vocabulary', 'kanji_reading', 2, 'MULTIPLE_CHOICE', '＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。', '<u>電気</u>を つけて ください。', '["てんぎ","てんき","でんぎ","でんき"]'::jsonb, 3, null, null, null, null, null, null, 'N5-mondai.pdf', 100, 'N5', 'official_sample', 2),
  ('n5-tp1', 'sample', 'vocabulary', 'vocab_writing', 3, 'MULTIPLE_CHOICE', '＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。', '<u>そと</u>で まちましょう。', '["(perlu verifikasi)","(perlu verifikasi)","(perlu verifikasi)","外"]'::jsonb, 3, null, null, null, null, null, null, 'N5-mondai.pdf', 100, 'N5', 'needs_review', 3),
  ('n5-tp1', 'sample', 'vocabulary', 'vocab_writing', 4, 'MULTIPLE_CHOICE', '＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。', 'あの <u>ほてる</u>は ゆうめいです。', '["ホラル","ホテル","ホラハ","ホテハ"]'::jsonb, 1, null, null, null, null, null, null, 'N5-mondai.pdf', 100, 'N5', 'official_sample', 4),
  ('n5-tp1', 'sample', 'vocabulary', 'context_vocab', 5, 'MULTIPLE_CHOICE', '（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。', 'あそこで タクシーに （　）。', '["のりました","あがりました","つきました","はいりました"]'::jsonb, 0, null, null, null, null, null, null, 'N5-mondai.pdf', 101, 'N5', 'official_sample', 5),
  ('n5-tp1', 'sample', 'vocabulary', 'context_vocab', 6, 'IMAGE_BASED', '（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。', 'ここは （　）です。 べんきょうできません。<br><small>Gambar: seorang anak menutup telinga sambil belajar, di sebelahnya orang bermain gitar keras-keras.</small>', '["くらい","さむい","うるさい","あぶない"]'::jsonb, 2, null, null, 'assets/images/jlpt-n5/vocab-q6.png', null, null, null, 'N5-mondai.pdf', 101, 'N5', 'official_sample', 6),
  ('n5-tp1', 'sample', 'vocabulary', 'synonym', 7, 'MULTIPLE_CHOICE', '＿＿＿の ぶんと だいたい おなじ いみの ぶんが あります。1・2・3・4から いちばん いい ものを ひとつ えらんでください。', 'わたしは <u>デパートに つとめて います</u>。', '["わたしは デパートで かいものを して います。","わたしは デパートで さんぽを して います。","わたしは デパートで しごとを して います。","わたしは デパートで やすんで います。"]'::jsonb, 2, null, null, null, null, null, null, 'N5-mondai.pdf', 102, 'N5', 'official_sample', 7),
  ('n5-tp1', 'sample', 'vocabulary', 'synonym', 8, 'MULTIPLE_CHOICE', '＿＿＿の ぶんと だいたい おなじ いみの ぶんが あります。1・2・3・4から いちばん いい ものを ひとつ えらんでください。', '<u>ゆうべ パーティーへ いきました。</u>', '["きのうの ひる パーティーへ いきました。","きのうの よる パーティーへ いきました。","おとといの ひる パーティーへ いきました。","おとといの よる パーティーへ いきました。"]'::jsonb, 1, null, null, null, null, null, null, 'N5-mondai.pdf', 102, 'N5', 'official_sample', 8),
  ('n5-tp1', 'sample', 'grammar_reading', 'sentence_grammar', 1, 'MULTIPLE_CHOICE', '（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。', '<ruby>弟<rt>おとうと</rt></ruby>は へや（　）そうじを しました。', '["が","を","に","の"]'::jsonb, 3, null, null, null, null, null, null, 'N5-mondai.pdf', 104, 'N5', 'official_sample', 9),
  ('n5-tp1', 'sample', 'grammar_reading', 'sentence_grammar', 2, 'MULTIPLE_CHOICE', '（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。', 'きのうは うちに （　）　<ruby>何<rt>なに</rt></ruby>を しましたか。', '["かえる","かえるから","かえって","かえったり"]'::jsonb, 2, null, null, null, null, null, null, 'N5-mondai.pdf', 104, 'N5', 'official_sample', 10),
  ('n5-tp1', 'sample', 'grammar_reading', 'sentence_arrangement', 3, 'SENTENCE_ARRANGEMENT', '★ に はいる ものは どれですか。1・2・3・4から いちばん いい ものを ひとつ えらんで、★ の ばしょに はいる ばんごうを こたえて ください。', 'これは きょねん わたし ＿＿＿ ＿＿＿ ★ ＿＿＿ しゃしんです。<br><small>Urutan lengkap: これはきょねんわたしが海でとったしゃしんです。(1が→4海→2で→3とった)</small>', '["が","で","とった","海"]'::jsonb, 1, null, null, null, null, null, null, 'N5-mondai.pdf', 105, 'N5', 'official_sample', 11),
  ('n5-tp1', 'sample', 'grammar_reading', 'sentence_arrangement', 4, 'SENTENCE_ARRANGEMENT', '★ に はいる ものは どれですか。1・2・3・4から いちばん いい ものを ひとつ えらんで、★ の ばしょに はいる ばんごうを こたえて ください。', 'きのう、＿＿＿ ＿＿＿ ★ ＿＿＿。<br><small>Urutan lengkap: きのう、日本語のじしょを買いに行きました。(2日本語の→4じしょを→1買いに→3行きました)</small>', '["買いに","日本語の","行きました","じしょを"]'::jsonb, 0, null, null, null, null, null, null, 'N5-mondai.pdf', 106, 'N5', 'official_sample', 12),
  ('n5-tp1', 'sample', 'grammar_reading', 'text_grammar', 5, 'CLOZE_TEST', '5 から 9 に 何を いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。', 'はじめまして。ジョン・スミスです。アメリカから ［５］。<br>わたしは えいがが 好きです。アメリカの えいがは よく 知っています。［６］、日本の えいがは あまり 知りません。日本では、日本の えいがを たくさん ［７］。<br>どうぞ よろしく おねがいします。', '["行きます","行きました","来ます","来ました"]'::jsonb, 3, null, 'cloze-john-selfintro', null, null, null, null, 'N5-mondai.pdf', 107, 'N5', 'official_sample', 13),
  ('n5-tp1', 'sample', 'grammar_reading', 'text_grammar', 6, 'CLOZE_TEST', '5 から 9 に 何を いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。', 'はじめまして。ジョン・スミスです。アメリカから ［５：来ました］。<br>わたしは えいがが 好きです。アメリカの えいがは よく 知っています。［６］、日本の えいがは あまり 知りません。日本では、日本の えいがを たくさん ［７］。<br>どうぞ よろしく おねがいします。', '["では","だから","でも","それから"]'::jsonb, 2, null, 'cloze-john-selfintro', null, null, null, null, 'N5-mondai.pdf', 107, 'N5', 'official_sample', 14),
  ('n5-tp1', 'sample', 'grammar_reading', 'text_grammar', 7, 'CLOZE_TEST', '5 から 9 に 何を いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。', 'はじめまして。ジョン・スミスです。アメリカから ［５：来ました］。<br>わたしは えいがが 好きです。アメリカの えいがは よく 知っています。［６：でも］、日本の えいがは あまり 知りません。日本では、日本の えいがを たくさん ［７］。<br>どうぞ よろしく おねがいします。', '["見ました","見たいです","見て いました","見るからです"]'::jsonb, 1, null, 'cloze-john-selfintro', null, null, null, null, 'N5-mondai.pdf', 108, 'N5', 'official_sample', 15),
  ('n5-tp1', 'sample', 'grammar_reading', 'text_grammar', 8, 'CLOZE_TEST', '5 から 9 に 何を いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。', 'みなさん、こんにちは。ヤンです。<br>わたしは 日本語学校で 毎日 べんきょうして います。今は、学校の ちかくに 姉と 住んで います。姉が いるから、［８］。<br>わたしは、日本で たくさん 友だちが ほしいです。みなさん、［９］。<br>どうぞ よろしく おねがいします。', '["さびしく ありません","さびしく ありませんでした","さびしく ありませんか","さびしく ありませんでしたか"]'::jsonb, 0, null, 'cloze-yan-selfintro', null, null, null, null, 'N5-mondai.pdf', 108, 'N5', 'official_sample', 16),
  ('n5-tp1', 'sample', 'grammar_reading', 'text_grammar', 9, 'CLOZE_TEST', '5 から 9 に 何を いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。', 'みなさん、こんにちは。ヤンです。<br>わたしは 日本語学校で 毎日 べんきょうして います。今は、学校の ちかくに 姉と 住んで います。姉が いるから、［８：さびしく ありません］。<br>わたしは、日本で たくさん 友だちが ほしいです。みなさん、［９］。<br>どうぞ よろしく おねがいします。', '["学校に 毎日 行きませんか","学校で 友だちと あそびました","うちに あそびに 来て ください","うちで 姉と あそびたいです"]'::jsonb, 2, null, 'cloze-yan-selfintro', null, null, null, null, 'N5-mondai.pdf', 108, 'N5', 'official_sample', 17),
  ('n5-tp1', 'sample', 'grammar_reading', 'short_reading', 10, 'READING_COMPREHENSION', 'つぎの ぶんを 読んで しつもんに こたえて ください。こたえは 1・2・3・4から いちばん いい ものを ひとつ えらんでください。', '<ruby>先生<rt>せんせい</rt></ruby>が アンナさんに <ruby>手紙<rt>てがみ</rt></ruby>を 書きました。<br><blockquote>アンナさん<br><br>今週は しごとが たくさん あります。土曜日と 日曜日も いそがしいです。<br>来週の 月曜日に 来て ください。</blockquote><br><small>先生は いつ 時間が ありますか。</small>', '["今週","土曜日","日曜日","月曜日"]'::jsonb, 3, null, 'reading-letter-anna', null, null, null, null, 'N5-mondai.pdf', 109, 'N5', 'official_sample', 18),
  ('n5-tp1', 'sample', 'grammar_reading', 'short_reading', 11, 'READING_COMPREHENSION', 'つぎの ぶんを 読んで しつもんに こたえて ください。こたえは 1・2・3・4から いちばん いい ものを ひとつ えらんでください。', 'ヤンさんの うちは 町の 中の べんりな ところに あります。<br>となりに パンやが あります。前は はなやで、はなやの となりは さかなやです。近くに くすりやと にくやも あります。ゆうびんきょくと びょういんも あります。<br>今日の ゆうがた、ヤンさんの 友だちが あそびに 来ます。ヤンさんは とりにくの りょうりと さかなの りょうりを 作ります。れいぞうこの 中に とりにくと さかなが ありませんから、ヤンさんは これから 買いものに でかけます。それから、ゆうびんきょくへ 行って、きってを 買います。<br><small>つぎの 中で、ヤンさんの うちから いちばん 近い 店は どれ ですか。</small>', '["にくや","パンや","くすりや","さかなや"]'::jsonb, 1, null, 'reading-yan-house', null, null, null, null, 'N5-mondai.pdf', 110, 'N5', 'official_sample', 19),
  ('n5-tp1', 'sample', 'grammar_reading', 'medium_reading', 12, 'READING_COMPREHENSION', 'つぎの ぶんを 読んで しつもんに こたえて ください。こたえは 1・2・3・4から いちばん いい ものを ひとつ えらんでください。', 'ヤンさんの うちは 町の 中の べんりな ところに あります。<br>となりに パンやが あります。前は はなやで、はなやの となりは さかなやです。近くに くすりやと にくやも あります。ゆうびんきょくと びょういんも あります。<br>今日の ゆうがた、ヤンさんの 友だちが あそびに 来ます。ヤンさんは とりにくの りょうりと さかなの りょうりを 作ります。れいぞうこの 中に とりにくと さかなが ありませんから、ヤンさんは これから 買いものに でかけます。それから、ゆうびんきょくへ 行って、きってを 買います。<br><small>ヤンさんは 今日 どこへ 行きますか。</small>', '["にくや、さかなや、ゆうびんきょく","パンや、くすりや、ゆうびんきょく","びょういん、はなや、さかなや","びょういん、にくや、パンや"]'::jsonb, 0, null, 'reading-yan-house', null, null, null, null, 'N5-mondai.pdf', 111, 'N5', 'official_sample', 20),
  ('n5-tp1', 'sample', 'grammar_reading', 'information_retrieval', 13, 'READING_COMPREHENSION', 'つぎの ぶんを 読んで、「電車の 時間」と「バスの 時間」を 見て、しつもんに こたえて ください。こたえは 1・2・3・4から いちばん いい ものを ひとつ えらんでください。', 'あした いちご山へ 行きます。東京駅から 中川駅まで 電車で 行って、中川駅から いちご山まで バスで 行きます。<br>いちご山に 午前11時ごろ 着きたいです。そして、電車は 安いほうが いいです。<table class="exam-table"><caption>電車の時間（東京駅→中川駅）</caption><tr><th></th><th>東京駅発</th><th>中川駅着</th></tr><tr><td>ふじ1</td><td>8:20</td><td>10:20</td></tr><tr><td>さくら1</td><td>9:10</td><td>10:10</td></tr><tr><td>ふじ3</td><td>9:20</td><td>11:20</td></tr><tr><td>さくら3</td><td>10:10</td><td>11:10</td></tr></table><small>お金：ふじ 3,000円　さくら 5,000円</small><table class="exam-table"><caption>バスの時間（中川駅→いちご山）</caption><tr><th>中川駅発</th><th>いちご山着</th></tr><tr><td>10:30</td><td>11:00</td></tr><tr><td>11:30</td><td>12:00</td></tr></table><small>お金：800円</small><br><small>電車は どれに 乗りますか。</small>', '["ふじ1","さくら1","ふじ3","さくら3"]'::jsonb, 0, null, 'reading-train-bus-schedule', null, null, null, null, 'N5-mondai.pdf', 112, 'N5', 'official_sample', 21),
  ('n5-tp1', 'sample', 'listening', 'task_comprehension', 1, 'AUDIO_IMAGE_CHOICE', 'もんだい1では、はじめに しつもんを きいて ください。それから はなしを きいて、もんだいようしの 1から4の なかから、ただしい こたえを ひとつ えらんで ください。', 'クラスで先生が話しています。学生は、今日、家で、どこを勉強しますか。<br>F：では、今日は20ページまで終わりましたから、21ページは宿題ですね。<br>M：全部ですか。<br>F：いえ、21ページの1番です。2番は、クラスでします。<br>学生は、今日、家で、どこを勉強しますか。', '["Halaman 20-21, kedua nomor dikerjakan (lingkaran besar)","Halaman 21 saja, kedua nomor (lingkaran di sisi kanan)","Halaman 21, nomor 1 saja (lingkaran kecil di kotak 1)","Halaman 21, nomor 2 saja (lingkaran kecil di kotak 2)"]'::jsonb, 2, null, null, 'assets/images/jlpt-n5/listen-p1-q1.png', 'assets/audio/n5-tp1-listening.mp3', null, null, 'N5-script.pdf', 151, 'N5', 'official_sample', 22),
  ('n5-tp1', 'sample', 'listening', 'task_comprehension', 2, 'AUDIO_IMAGE_CHOICE', 'もんだい1では、はじめに しつもんを きいて ください。それから はなしを きいて、もんだいようしの 1から4の なかから、ただしい こたえを ひとつ えらんで ください。', '海の公園で、先生が学生に話しています。学生ははじめに何をしますか。<br>F：この海の公園では遊ぶ前に、映画を見ながら、海の勉強をします。ここでは、切符がいりますから、はじめに切符を買ってきてください。それから、映画を見ましょう。<br>学生ははじめに何をしますか。', '["Bermain bola di pantai","Menonton film akuarium di bioskop","Membaca buku di rak buku","Membeli tiket di loket"]'::jsonb, 3, null, null, 'assets/images/jlpt-n5/listen-p1-q2.png', 'assets/audio/n5-tp1-listening.mp3', null, null, 'N5-script.pdf', 151, 'N5', 'official_sample', 23),
  ('n5-tp1', 'sample', 'listening', 'point_comprehension', 1, 'AUDIO_IMAGE_CHOICE', 'もんだい2では、はじめに しつもんを きいて ください。それから はなしを きいて、もんだいようしの 1から4の なかから、ただしい こたえを ひとつ えらんで ください。', '女の人と男の人が写真を見ながら話しています。田中さんの妹はどの人ですか。<br>F：ああ、この男の人が田中さんですか。<br>M：ええ。その隣の人が奥さんで、前にいる女の子が田中さんの子どもです。<br>F：かわいいですね。この帽子をかぶっている人は誰ですか。<br>M：田中さんの妹さんです。<br>F：そうですか。じゃ、このめがねをかけている人は？<br>M：あ、そちらは妹さんの友だちです。<br>田中さんの妹はどの人ですか。', '["Orang nomor 1 (istri, di sebelah Tanaka)","Orang nomor 2 (anak kecil)","Orang nomor 3 (memakai topi)","Orang nomor 4 (memakai kacamata)"]'::jsonb, 2, null, null, 'assets/images/jlpt-n5/listen-p2-q1.png', 'assets/audio/n5-tp1-listening.mp3', null, null, 'N5-script.pdf', 151, 'N5', 'official_sample', 24),
  ('n5-tp1', 'sample', 'listening', 'point_comprehension', 2, 'AUDIO_IMAGE_CHOICE', 'もんだい2では、はじめに しつもんを きいて ください。それから はなしを きいて、もんだいようしの 1から4の なかから、ただしい こたえを ひとつ えらんで ください。', '男の人と女の人が話しています。女の人は、あしたの午後、何をしますか。<br>M：あした、一緒に映画を見に行きませんか。<br>F：すみません、ちょっと…<br>M：いそがしいですか？<br>F：ええ、朝は洗濯したり、部屋を掃除したりします。それから来週はテストもありますよね？<br>M：え、テスト来週ですか！知りませんでした。いつですか。<br>F：来週の月曜日ですよ。だから、午後は勉強します。<br>M：ああ、僕もそうします。<br>女の人は、あしたの午後、何をしますか。', '["Menonton film di bioskop","Mencuci pakaian","Menyedot debu kamar","Belajar di meja"]'::jsonb, 3, null, null, 'assets/images/jlpt-n5/listen-p2-q2.png', 'assets/audio/n5-tp1-listening.mp3', null, null, 'N5-script.pdf', 152, 'N5', 'official_sample', 25),
  ('n5-tp1', 'sample', 'listening', 'verbal_expression', 1, 'AUDIO_MULTIPLE_CHOICE', 'もんだい3は、えを みながら しつもんを きいて ください。（や じるし）の ひとは なんと いいますか。1から3の なかから、いちばん いい ものを ひとつ えらんで ください。<br><small>Situasi: di sebuah restoran.</small>', 'レストランでお店の人を呼びます。何と言いますか。', '["いらっしゃいませ。","失礼しました。","すみません。"]'::jsonb, 2, null, null, null, 'assets/audio/n5-tp1-listening.mp3', null, null, 'N5-script.pdf', 152, 'N5', 'official_sample', 26),
  ('n5-tp1', 'sample', 'listening', 'verbal_expression', 2, 'AUDIO_MULTIPLE_CHOICE', 'もんだい3は、えを みながら しつもんを きいて ください。（や じるし）の ひとは なんと いいますか。1から3の なかから、いちばん いい ものを ひとつ えらんで ください。<br><small>Situasi: ingin memakai kamus milik teman.</small>', '友達の辞書を使いたいです。何と言いますか。', '["この辞書、ありがとうございました。","この辞書、貸してください。","この辞書、いいですよ。"]'::jsonb, 1, null, null, null, 'assets/audio/n5-tp1-listening.mp3', null, null, 'N5-script.pdf', 152, 'N5', 'official_sample', 27),
  ('n5-tp1', 'sample', 'listening', 'quick_response', 1, 'AUDIO_RESPONSE', 'もんだい4は、えが ありません。まず ぶんを きいて ください。それから、その へんじを きいて、1から3の なかから、いちばん いい ものを ひとつ えらんで ください。', 'F：お国はどちらですか。', '["あちらです。","アメリカです。","部屋です。"]'::jsonb, 1, null, null, null, 'assets/audio/n5-tp1-listening.mp3', null, null, 'N5-script.pdf', 153, 'N5', 'official_sample', 28),
  ('n5-tp1', 'sample', 'listening', 'quick_response', 2, 'AUDIO_RESPONSE', 'もんだい4は、えが ありません。まず ぶんを きいて ください。それから、その へんじを きいて、1から3の なかから、いちばん いい ものを ひとつ えらんで ください。', 'F：お茶、どうぞ。', '["ありがとうございます。","いかがですか。","どういたしまして。"]'::jsonb, 0, null, null, null, 'assets/audio/n5-tp1-listening.mp3', null, null, 'N5-script.pdf', 153, 'N5', 'official_sample', 29);
