const examEmbedMode=new URLSearchParams(location.search).get("embed")==="1";
document.body.classList.toggle("embed-mode",examEmbedMode);
const questionBankReady=true;
const defaultQuestions=[
  {category:"Kosakata",instruction:"Pilih arti yang paling tepat.",html:"<ruby>学生<rt>がくせい</rt></ruby>",options:["Guru","Pelajar","Pegawai","Dokter"],answer:1,explanation:"学生（がくせい） berarti pelajar atau mahasiswa. 先生 adalah guru dan 医者 adalah dokter.",material:"Bab 1 · Perkenalan dan profesi"},
  {category:"Kanji",instruction:"Pilih cara baca kanji yang benar.",html:"<ruby>病院<rt>びょういん</rt></ruby>",options:["びよういん","びょういん","びょいん","びょうえん"],answer:1,explanation:"病院 dibaca びょういん (byouin) dan berarti rumah sakit. Perhatikan bunyi panjang びょう.",material:"Bab 1 · Kosakata tempat"},
  {category:"Tata bahasa",instruction:"Pilih kata yang tepat untuk melengkapi kalimat.",html:"これは わたし（　）ほんです。",options:["は","を","の","に"],answer:2,explanation:"Partikel の menghubungkan dua kata benda dan menunjukkan kepemilikan: わたしのほん berarti buku saya.",material:"Bab 2 · Pola N1 の N2"},
  {category:"Tata bahasa",instruction:"Pilih partikel yang tepat.",html:"まいあさ 7<ruby>時<rt>じ</rt></ruby>（　）おきます。",options:["で","に","を","へ"],answer:1,explanation:"Partikel に digunakan setelah waktu yang spesifik. 7時におきます berarti bangun pukul tujuh.",material:"Bab 4 · Waktu dan kegiatan"},
  {category:"Susunan kalimat",instruction:"Pilih susunan kalimat yang benar.",html:"“Saya pergi ke sekolah dengan bus.”",options:["バスで 学校へ 行きます。","学校で バスへ 行きます。","バスへ 学校で 行きます。","学校を バスに 行きます。"],answer:0,explanation:"Urutan yang alami adalah alat transportasi + で, tujuan + へ, lalu kata kerja: バスで 学校へ 行きます。",material:"Bab 5 · Perjalanan dan perpindahan"},
  {category:"Melengkapi kalimat",instruction:"Pilih bentuk kata kerja yang sesuai.",html:"きょうは <ruby>日曜日<rt>にちようび</rt></ruby>ですから、<ruby>会社<rt>かいしゃ</rt></ruby>へ（　）。",options:["行きます","行きません","行きました","行って"],answer:1,explanation:"Karena hari ini Minggu, pembicara tidak pergi ke kantor. Bentuk negatif sopan dari 行きます adalah 行きません.",material:"Bab 4 · Bentuk positif dan negatif"},
  {category:"Bacaan",instruction:"Baca teks pendek, lalu jawab pertanyaannya.",html:"わたしは マリアです。<ruby>毎朝<rt>まいあさ</rt></ruby> 6<ruby>時<rt>じ</rt></ruby>に おきます。7<ruby>時半<rt>じはん</rt></ruby>に <ruby>会社<rt>かいしゃ</rt></ruby>へ <ruby>行<rt>い</rt></ruby>きます。<br><small>マリアさんは なんじに 会社へ 行きますか。</small>",options:["6時","6時半","7時","7時半"],answer:3,explanation:"Kalimat 7時半に会社へ行きます menyatakan Maria pergi ke kantor pukul 07.30.",material:"Bab 4–5 · Membaca jadwal"},
  {category:"Mendengarkan",instruction:"Dengarkan audio, lalu pilih kalimat yang diucapkan.",html:"音声を聞いてください。",audio:"駅はどこですか。",options:["えきは どこですか。","いえは どこですか。","えきは ここですか。","みせは どこですか。"],answer:0,explanation:"Audio berbunyi 駅はどこですか（えきは どこですか）, artinya “Stasiun ada di mana?”.",material:"Bab 3 · Tempat dan arah"},
  {category:"Kanji",instruction:"Pilih arti kanji yang benar.",html:"<ruby>先生<rt>せんせい</rt></ruby>",options:["Peneliti","Pelajar","Guru","Pegawai"],answer:2,explanation:"先生（せんせい） berarti guru atau dosen. Kanji 先 bermakna dahulu/depan dan 生 berkaitan dengan hidup/lahir.",material:"Bab 1 · Profesi"},
  {category:"Situasi",instruction:"Pilih ungkapan yang paling sesuai dengan situasi.",html:"Di restoran, kamu ingin meminta air dengan sopan.",options:["みずを ください。","みずを いきます。","みずが います。","みずで ください。"],answer:0,explanation:"Pola benda + をください digunakan untuk meminta sesuatu dengan sopan: みずをください berarti “Tolong beri saya air.”",material:"Bab 7 · Meminta dan memberi"},
];

const $=id=>document.getElementById(id);
const testTypeLabels={vocabulary:"Kosakata",kanji:"Kanji",grammar:"Tata Bahasa",sentence:"Susunan Kalimat",reading:"Bacaan",audio:"Audio",situational:"Situasional"};
let questions=[...defaultQuestions],examType="jlpt",testType="vocabulary",rangeStart=1,current=0,mode="simulation",answers=Array(questions.length).fill(null),checked=Array(questions.length).fill(false),flags=Array(questions.length).fill(false),furigana=true,timerId=null,seconds=720,reviewOnly=false,reviewIndexes=[];
function shuffled(values){return [...values].sort(()=>Math.random()-.5)}
function collectRangeData(source){const rows=[];for(let bab=rangeStart;bab<rangeStart+5;bab++)(source[bab]||[]).forEach(item=>rows.push({item,bab}));return rows}
function optionSet(correct,pool){return shuffled([correct,...shuffled(pool.filter(value=>value&&value!==correct)).slice(0,3)])}
function vocabularyQuestions(){const source=collectRangeData(babKosakataData),rows=shuffled(source).slice(0,10),meanings=source.map(row=>row.item[1]);return rows.map(({item,bab})=>{const options=optionSet(item[1],meanings);return{category:"Kosakata",instruction:"Pilih arti kosakata yang paling tepat.",html:item[0],options,answer:options.indexOf(item[1]),explanation:`${item[0]} berarti “${item[1]}”. Kosakata ini berasal dari Bab ${bab}.`,material:`Bab ${bab} · Kosakata`}})}
function kanjiQuestions(){const source=collectRangeData(babKanjiData),rows=shuffled(source).slice(0,10),readings=source.map(row=>row.item[1]);return rows.map(({item,bab})=>{const options=optionSet(item[1],readings);return{category:"Kanji",instruction:"Pilih cara baca kanji yang benar.",html:`<ruby>${item[0]}<rt>${item[1]}</rt></ruby>`,options,answer:options.indexOf(item[1]),explanation:`${item[0]} dibaca ${item[1]} dan berarti “${item[2]}”.`,material:`Bab ${bab} · Kanji dan cara baca`}})}
function grammarQuestions(){const result=[];for(let bab=rangeStart;bab<rangeStart+5;bab++){const item=tailoredQuizData[bab];if(item)result.push({category:"Tata Bahasa",instruction:`Pilih jawaban yang sesuai dengan pola Bab ${bab}.`,html:item[0],options:item[1],answer:item[2],explanation:item[3],material:`Bab ${bab} · Tata bahasa`})}return result}
function contextualQuestions(kind){const source=collectRangeData(babKanjiData),rows=shuffled(source).slice(0,10),allWords=source.map(row=>row.item[0]),allMeanings=source.map(row=>row.item[2]);return rows.map(({item,bab})=>{const [word,reading,meaning]=item;
  if(kind==="sentence"){const correct=`${word}を おぼえます。`,options=optionSet(correct,[`${word}が おぼえます。`,`${word}へ おぼえます。`,`おぼえます ${word}を。`]);return{category:"Susunan Kalimat",instruction:"Pilih susunan kalimat yang paling tepat.",html:`“Saya menghafalkan ${meaning}.”`,options,answer:options.indexOf(correct),explanation:`Objek ditandai を dan diletakkan sebelum kata kerja: ${correct}`,material:`Bab ${bab} · Kosakata dalam kalimat`}}
  if(kind==="reading"){const options=optionSet(meaning,allMeanings);return{category:"Bacaan",instruction:"Baca kalimat pendek, lalu pilih maknanya.",html:`これは <ruby>${word}<rt>${reading}</rt></ruby> です。`,options,answer:options.indexOf(meaning),explanation:`Kata ${word} (${reading}) pada teks berarti “${meaning}”.`,material:`Bab ${bab} · Bacaan pendek`}}
  if(kind==="audio"){const options=optionSet(word,allWords);return{category:"Audio",instruction:"Dengarkan audio, lalu pilih kata yang diucapkan.",html:"音声を聞いてください。",audio:reading,options,answer:options.indexOf(word),explanation:`Audio mengucapkan ${reading}, yaitu ${word} yang berarti “${meaning}”.`,material:`Bab ${bab} · Pemahaman audio`}}
  const correct=`${word}を ください。`,options=optionSet(correct,[`${word}へ ください。`,`${word}が ください。`,`${word}で ください。`]);return{category:"Situasional",instruction:"Pilih ungkapan yang paling sesuai dengan situasi.",html:`Kamu ingin meminta “${meaning}” dengan sopan.`,options,answer:options.indexOf(correct),explanation:`Pola benda + をください digunakan untuk meminta sesuatu dengan sopan: ${correct}`,material:`Bab ${bab} · Komunikasi praktis`}})}
function buildSelectedQuestions(){
  const vocabulary=vocabularyQuestions(),kanji=kanjiQuestions(),grammar=grammarQuestions(),sentence=contextualQuestions("sentence"),reading=contextualQuestions("reading"),audio=contextualQuestions("audio"),situational=contextualQuestions("situational");
  questions=examType==="jlpt"?[...vocabulary.slice(0,2),...kanji.slice(0,2),...grammar.slice(0,2),sentence[0],...reading.slice(0,2),audio[0]]:[...vocabulary.slice(0,2),...reading.slice(0,2),...audio.slice(0,3),...situational.slice(0,3)];
  questions=questions.filter(Boolean);if(!questions.length)questions=[...defaultQuestions];$("heroQuestionTotal").textContent=questions.length;$("heroPackage").textContent=`Bab ${rangeStart}–${rangeStart+4}`;
}
function updatePackagePreview(){const label=examType==="jlpt"?"Simulasi JLPT":"Simulasi JFT-Basic";$("selectedTestName").textContent=`${label} · Bab ${rangeStart}–${rangeStart+4}`;$("selectedRangeText").textContent=`Materi gabungan diambil dari Bab ${rangeStart}, ${rangeStart+1}, ${rangeStart+2}, ${rangeStart+3}, dan ${rangeStart+4}.`;$("heroExamType").textContent=examType==="jlpt"?"JLPT":"JFT";$("heroPackage").textContent=`Bab ${rangeStart}–${rangeStart+4}`}
function speak(text){if(!("speechSynthesis" in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="ja-JP";u.rate=.82;speechSynthesis.speak(u)}
function activeQuestionIndex(){return reviewOnly?reviewIndexes[current]:current}
function renderNavigator(){
  const grid=$("numberGrid");grid.replaceChildren();
  questions.forEach((_,index)=>{const b=document.createElement("button");b.textContent=index+1;b.classList.toggle("current",index===activeQuestionIndex());b.classList.toggle("answered",answers[index]!==null);b.classList.toggle("flagged",flags[index]);b.onclick=()=>{reviewOnly=false;current=index;renderQuestion()};grid.append(b)});
  $("answeredCount").textContent=`${answers.filter(v=>v!==null).length} / ${questions.length}`;$("temporaryScore").textContent=questions.filter((q,i)=>checked[i]&&answers[i]===q.answer).length;$("flaggedCount").textContent=flags.filter(Boolean).length;
}
function renderQuestion(){
  const index=activeQuestionIndex(),q=questions[index];
  $("categoryBadge").textContent=q.category.toUpperCase();$("questionCounter").textContent=reviewOnly?`Tinjauan ${current+1} dari ${reviewIndexes.length}`:`Soal ${index+1} dari ${questions.length}`;$("instruction").textContent=q.instruction;$("questionText").innerHTML=q.html;$("questionText").classList.toggle("hide-furigana",!furigana);$("testProgress").style.width=`${((reviewOnly?current:index)+1)/(reviewOnly?reviewIndexes.length:questions.length)*100}%`;
  $("audioButton").hidden=!q.audio;if(q.audio)$("audioButton").onclick=()=>speak(q.audio);
  const box=$("answers");box.replaceChildren();q.options.forEach((option,choice)=>{const b=document.createElement("button");b.innerHTML=`<b>${String.fromCharCode(65+choice)}</b><span></span>`;b.querySelector("span").textContent=option;b.classList.toggle("selected",answers[index]===choice);if(checked[index]||reviewOnly){b.disabled=true;b.classList.toggle("correct",choice===q.answer);b.classList.toggle("wrong",answers[index]===choice&&choice!==q.answer)}b.onclick=()=>{answers[index]=choice;renderQuestion()};box.append(b)});
  const showExplanation=(checked[index]&&mode==="practice")||reviewOnly;$("explanation").hidden=!showExplanation;if(showExplanation){const correct=answers[index]===q.answer;$("explanation").className=`explanation${correct?"":" wrong"}`;$("explanation").innerHTML=`<b>${correct?"Jawaban benar":"Belum tepat"}</b>${q.explanation}`}
  $("flagQuestion").classList.toggle("active",flags[index]);$("flagQuestion").textContent=flags[index]?"★ Ditandai":"☆ Tandai soal";$("previousQuestion").disabled=current===0;$("checkAnswer").hidden=reviewOnly||checked[index]||mode==="simulation";$("checkAnswer").textContent="Periksa jawaban";$("nextQuestion").hidden=reviewOnly||(!checked[index]&&mode==="practice");$("nextQuestion").textContent=index===questions.length-1?"Lihat hasil →":"Soal berikutnya →";
  if(mode==="simulation"&&!reviewOnly){$("checkAnswer").hidden=false;$("checkAnswer").textContent=index===questions.length-1?"Simpan & lihat hasil":"Simpan & berikutnya"}
  renderNavigator();
}
function checkOrAdvance(){
  const index=activeQuestionIndex();if(answers[index]===null){$("explanation").hidden=false;$("explanation").className="explanation wrong";$("explanation").innerHTML="<b>Pilih satu jawaban terlebih dahulu.</b>Setelah memilih, jawaban dapat diperiksa.";return}
  checked[index]=true;if(mode==="simulation"){if(index===questions.length-1)finishTest();else{current++;renderQuestion()}}else renderQuestion();
}
function advance(){if(activeQuestionIndex()===questions.length-1)finishTest();else{current++;renderQuestion()}}
function categoryScores(){const result={};questions.forEach((q,i)=>{result[q.category]??={correct:0,total:0};result[q.category].total++;if(answers[i]===q.answer)result[q.category].correct++});return result}
function finishTest(){
  clearInterval(timerId);checked=checked.map(()=>true);const correct=questions.filter((q,i)=>answers[i]===q.answer).length,score=Math.round(correct/questions.length*100);$("testScreen").hidden=true;$("resultScreen").hidden=false;$("finalScore").textContent=score;$("resultTitle").textContent=score>=80?"Fondasi kamu sudah kuat.":score>=60?"Fondasi sudah terbentuk.":"Mari perkuat dasar sedikit lagi.";$("resultSummary").textContent=`${correct} dari ${questions.length} soal benar. ${questions.length-correct} soal tersimpan dalam bank kesalahan untuk ditinjau kembali.`;
  const categoryBox=$("categoryResults");categoryBox.replaceChildren();Object.entries(categoryScores()).forEach(([name,value])=>{const pct=Math.round(value.correct/value.total*100),row=document.createElement("div");row.innerHTML=`<span>${name}</span><i style="--score:${pct}%"></i><b>${pct}%</b>`;categoryBox.append(row)});
  const weakest=Object.entries(categoryScores()).sort((a,b)=>a[1].correct/a[1].total-b[1].correct/b[1].total).slice(0,2);$("recommendations").innerHTML=weakest.map(([name])=>`<div><b>Perkuat ${name}</b>Ulangi materi dan latihan terkait sebelum mencoba simulasi berikutnya.</div>`).join("")+`<div><b>Ulangi bank kesalahan</b>Fokuskan sesi berikutnya pada ${questions.length-correct} soal yang masih salah.</div>`;
  reviewIndexes=questions.map((q,i)=>answers[i]!==q.answer?i:-1).filter(i=>i>=0);const list=$("mistakeList");list.replaceChildren();reviewIndexes.forEach(i=>{const q=questions[i],a=document.createElement("article");a.innerHTML=`<b>Soal ${i+1} · ${q.category}</b><p>Jawabanmu: ${answers[i]===null?"Belum dijawab":q.options[answers[i]]} · Jawaban benar: ${q.options[q.answer]}</p><p>${q.explanation}</p><small>Pelajari kembali: ${q.material}</small>`;list.append(a)});window.scrollTo({top:0,behavior:"smooth"});
}
function startTimer(){clearInterval(timerId);seconds=720;$("timer").textContent="12:00";if(!$("timerEnabled").checked){$("timer").textContent="Tanpa timer";return}timerId=setInterval(()=>{seconds--;const m=String(Math.floor(seconds/60)).padStart(2,"0"),s=String(seconds%60).padStart(2,"0");$("timer").textContent=`${m}:${s}`;if(seconds<=0)finishTest()},1000)}
function startTest(){if(!questionBankReady)return;buildSelectedQuestions();current=0;answers=Array(questions.length).fill(null);checked=Array(questions.length).fill(false);flags=Array(questions.length).fill(false);reviewOnly=false;$("startScreen").hidden=true;$("resultScreen").hidden=true;$("testScreen").hidden=false;startTimer();renderQuestion();window.scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll("#examChoice button").forEach(button=>button.onclick=()=>{examType=button.dataset.exam;document.querySelectorAll("#examChoice button").forEach(item=>item.classList.toggle("active",item===button));updatePackagePreview()});
$("chapterRange").onchange=()=>{rangeStart=Number($("chapterRange").value);updatePackagePreview()};
document.querySelectorAll("#modeChoice button").forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll("#modeChoice button").forEach(x=>x.classList.toggle("active",x===b))});
updatePackagePreview();
$("startTest").onclick=startTest;$("checkAnswer").onclick=checkOrAdvance;$("nextQuestion").onclick=advance;$("previousQuestion").onclick=()=>{if(current>0){current--;renderQuestion()}};$("flagQuestion").onclick=()=>{const i=activeQuestionIndex();flags[i]=!flags[i];renderQuestion()};$("furiganaToggle").onclick=()=>{furigana=!furigana;$("furiganaToggle").textContent=`振 Furigana: ${furigana?"aktif":"mati"}`;renderQuestion()};$("finishEarly").onclick=finishTest;$("restartTest").onclick=()=>{$("resultScreen").hidden=true;$("startScreen").hidden=false;window.scrollTo({top:0,behavior:"smooth"})};$("reviewMistakes").onclick=()=>{$("mistakeBank").hidden=false;$("mistakeBank").scrollIntoView({behavior:"smooth"})};$("closeMistakes").onclick=()=>{$("mistakeBank").hidden=true};
