const examEmbedMode=new URLSearchParams(location.search).get("embed")==="1";
document.body.classList.toggle("embed-mode",examEmbedMode);
const questionBankReady=true;
const defaultQuestions=[
  {category:"Kosakata",instruction:"Pilih arti yang paling tepat.",html:"<ruby>学生<rt>がくせい</rt></ruby>",options:["Guru","Pelajar","Pegawai","Dokter"],answer:1,explanation:"学生（がくせい） berarti pelajar atau mahasiswa. 先生 adalah guru dan 医者 adalah dokter.",material:"Bab 1 · Perkenalan dan profesi"},
  {category:"Kanji",instruction:"Pilih cara baca kanji yang benar.",html:"<ruby>病院<rt>びょういん</rt></ruby>",options:["びよういん","びょういん","びょいん","びょうえん"],answer:1,explanation:"病院 dibaca びょういん (byouin) dan berarti rumah sakit. Perhatikan bunyi panjang びょう.",material:"Bab 1 · Kosakata tempat"},
  {category:"Tata bahasa",instruction:"Pilih kata yang tepat untuk melengkapi kalimat.",html:"これは わたし（　）ほんです。",options:["は","を","の","に"],answer:2,explanation:"Partikel の menghubungkan dua kata benda dan menunjukkan kepemilikan: わたしのほん berarti buku saya.",material:"Bab 2 · Pola N1 の N2"},
  {category:"Tata bahasa",instruction:"Pilih partikel yang tepat.",html:"まいあさ 7<ruby>時<rt>じ</rt></ruby>（　）おきます。",options:["で","に","を","へ"],answer:1,explanation:"Partikel に digunakan setelah waktu yang spesifik. 7時におきます berarti bangun pukul tujuh.",material:"Bab 4 · Waktu dan kegiatan"},
  {category:"Susunan kalimat",instruction:"Pilih susunan kalimat yang benar.",html:"“Saya pergi ke sekolah dengan bus.”",options:["バスで 学校へ 行きます。","学校で バスへ 行きます。","バスへ 学校で 行きます。","学校を バスに 行きます。"],answer:0,explanation:"Urutan yang alami adalah alat transportasi + で, tujuan + へ, lalu kata kerja: バスで 学校へ 行きます。",material:"Bab 5 · Perjalanan dan perpindahan"},
  {category:"Melengkapi kalimat",instruction:"Pilih bentuk kata kerja yang sesuai.",html:"きょうは <ruby>日曜日<rt>にちようび</rt></ruby>ですから、<ruby>会社<rt>かいしゃ</rt></ruby>へ（　）。",options:["行きます","行きません","行きました","行って"],answer:1,explanation:"Karena hari ini Minggu, pembicara tidak pergi ke kantor. Bentuk negatif sopan dari 行きます adalah 行きません.",material:"Bab 4 · Bentuk positif dan negatif"},
  {category:"Bacaan",instruction:"Baca teks pendek, lalu jawab pertanyaannya.",html:"わたしは マリアです。<ruby>毎朝<rt>まいあさ</rt></ruby> 6<ruby>時<rt>じ</rt></ruby>に おきます。7<ruby>時半<rt>じはん</rt></ruby>に <ruby>会社<rt>かいしゃ</rt></ruby>へ <ruby>行<rt>い</rt></ruby>きます。<br><small>マリアさんは なんじに 会社へ 行きますか。</small>",options:["6時","6時半","7時","7時半"],answer:3,explanation:"Kalimat 7時半に会社へ行きます menyatakan Maria pergi ke kantor pukul 07.30.",material:"Bab 4–5 · Membaca jadwal"},
  {category:"Mendengarkan",instruction:"Dengarkan audio, lalu pilih kalimat yang diucapkan.",html:"音声を聞いてください。",audio:"駅はどこですか。",options:["えきは どこですか。","いえは どこですか。","えきは ここですか。","みせは どこですか。"],answer:0,explanation:"Audio berbunyi 駅はどこですか（えきは どこですか）, artinya “Stasiun ada di mana?”.",material:"Bab 3 · Tempat dan arah"},
  {category:"Kanji",instruction:"Pilih arti kanji yang benar.",html:"<ruby>先生<rt>せんせい</rt></ruby>",options:["Peneliti","Pelajar","Guru","Pegawai"],answer:2,explanation:"先生（せんせい） berarti guru atau dosen. Kanji 先 bermakna dahulu/depan dan 生 berkaitan dengan hidup/lahir.",material:"Bab 1 · Profesi"},
  {category:"Situasi",instruction:"Pilih ungkapan yang paling sesuai dengan situasi.",html:"Di restoran, kamu ingin meminta air dengan sopan.",options:["みずを ください。","みずを いきます。","みずが います。","みずで ください。"],answer:0,explanation:"Pola benda + をください digunakan untuk meminta sesuatu dengan sopan: みずをください berarti “Tolong beri saya air.”",material:"Bab 7 · Meminta dan memberi"},
];
/* Paket soal siap pakai (bukan hasil generator acak per-bab) - format ujian
   resmi (4 mondai) supaya siswa juga bisa berlatih di luar paket per-bab. */
const mockTestPackages={
  "d03":{
    label:"Paket Ujian · Kosakata & Kanji (Set 03)",
    questions:[
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"<u>西</u>の そらに ほしが みえます。",options:["ひがし","にし","きた","みなみ"],answer:1,explanation:"西 dibaca “にし” dan berarti arah barat. 東=ひがし(timur), 北=きた(utara), 南=みなみ(selatan).",material:"Paket D03 — Mondai 1 No.1"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"あの<u>白い</u> いえが わたしの いえです。",options:["ひろい","とおい","しろい","ひくい"],answer:2,explanation:"白い dibaca “しろい” dan berarti putih. ひろい=luas, とおい=jauh, ひくい=rendah.",material:"Paket D03 — Mondai 1 No.2"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"なつに <u>海</u>へ いきました。",options:["やま","かわ","しま","うみ"],answer:3,explanation:"海 dibaca “うみ” dan berarti laut. 山=やま(gunung), 川=かわ(sungai), 島=しま(pulau).",material:"Paket D03 — Mondai 1 No.3"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"ちちは いま ソファで <u>休んで</u> います。",options:["やすんで","のんで","ならんで","よろこんで"],answer:0,explanation:"休んで dibaca “やすんで”, dari kata kerja 休む (beristirahat).",material:"Paket D03 — Mondai 1 No.4"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"<u>来週</u> くにへ かえります。",options:["らいしゅ","らいしゅう","らしゅ","らしゅう"],answer:1,explanation:"来週 dibaca “らいしゅう” dan berarti minggu depan. Perhatikan bunyi panjang しゅう.",material:"Paket D03 — Mondai 1 No.5"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"りんごを <u>五つ</u> かいました。",options:["ごつ","いつ","いつつ","ごうつ"],answer:2,explanation:"五つ dibaca “いつつ”, bilangan asli Jepang untuk lima buah (ひとつ・ふたつ・みっつ・よっつ・いつつ…).",material:"Paket D03 — Mondai 1 No.6"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"せまい <u>道</u>を とおります。",options:["とち","にわ","はし","みち"],answer:3,explanation:"道 dibaca “みち” dan berarti jalan.",material:"Paket D03 — Mondai 1 No.7"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"きょうの <u>午後</u> ともだちに あいます。",options:["ごご","ごうご","ごごう","ごうごう"],answer:0,explanation:"午後 dibaca “ごご” dan berarti siang/sore (setelah tengah hari).",material:"Paket D03 — Mondai 1 No.8"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"つくえの <u>上</u>に なにが ありますか。",options:["なか","した","うえ","よこ"],answer:2,explanation:"上 dibaca “うえ” dan berarti atas.",material:"Paket D03 — Mondai 1 No.9"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"みせに ひとが <u>十人</u> います。",options:["じゅにん","じゅうにん","じゅじん","じゅうじん"],answer:1,explanation:"十人 dibaca “じゅうにん”, sepuluh orang. Perhatikan bunyi panjang じゅう.",material:"Paket D03 — Mondai 1 No.10"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"<u>外国</u>に いきたいです。",options:["かいこく","かいごく","がいごく","がいこく"],answer:3,explanation:"外国 dibaca “がいこく” dan berarti luar negeri.",material:"Paket D03 — Mondai 1 No.11"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"この えいがは <u>長い</u>です。",options:["ながい","やすい","たのしい","あたらしい"],answer:0,explanation:"長い dibaca “ながい” dan berarti panjang/lama.",material:"Paket D03 — Mondai 1 No.12"},
      {category:"Penulisan Kanji",instruction:"＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"こどもたちが こうえんを <u>あるいて</u> います。",options:["走いて","足いて","歩いて","促いて"],answer:2,explanation:"あるいて ditulis 歩いて, dari kata kerja 歩く (berjalan).",material:"Paket D03 — Mondai 2 No.13"},
      {category:"Penulisan Kanji",instruction:"＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"<u>ぱそこん</u>で しごとを します。",options:["パンコソ","パソコン","バツコシ","バシコツ"],answer:1,explanation:"ぱそこん (komputer) ditulis dengan katakana パソコン — perhatikan bentuk huruf yang mirip.",material:"Paket D03 — Mondai 2 No.14"},
      {category:"Penulisan Kanji",instruction:"＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"ほんを <u>よんで</u> ください。",options:["読んで","語んで","話んで","伺んで"],answer:0,explanation:"よんで ditulis 読んで, dari kata kerja 読む (membaca).",material:"Paket D03 — Mondai 2 No.15"},
      {category:"Penulisan Kanji",instruction:"＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"きょうは <u>てんき</u>が いいですね。",options:["夫木","天木","夫気","天気"],answer:3,explanation:"てんき (cuaca) ditulis 天気.",material:"Paket D03 — Mondai 2 No.16"},
      {category:"Penulisan Kanji",instruction:"＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"きのうは <u>しんぶん</u>を よみませんでした。",options:["新文","新聞","親文","親聞"],answer:1,explanation:"しんぶん (koran) ditulis 新聞.",material:"Paket D03 — Mondai 2 No.17"},
      {category:"Penulisan Kanji",instruction:"＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"ちかくに <u>ふるい</u> アパートが あります。",options:["由い","百い","古い","苦い"],answer:2,explanation:"ふるい (tua/lama) ditulis 古い.",material:"Paket D03 — Mondai 2 No.18"},
      {category:"Penulisan Kanji",instruction:"＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"<u>とも</u>だちと いっしょに がっこうへ いきます。",options:["支","反","有","友"],answer:3,explanation:"とも(だち) ditulis 友, dari kata 友だち (teman).",material:"Paket D03 — Mondai 2 No.19"},
      {category:"Penulisan Kanji",instruction:"＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"<u>じかん</u>が ありません。",options:["時間","時問","寺間","寺問"],answer:0,explanation:"じかん (waktu) ditulis 時間. Hati-hati membedakan 間 dengan 問 yang bentuknya mirip.",material:"Paket D03 — Mondai 2 No.20"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"（　）で かいものを しましょう。",options:["スプーン","スーパー","スペース","スポーツ"],answer:1,explanation:"“Ayo berbelanja di ___.” Jawaban yang tepat adalah スーパー (supermarket).",material:"Paket D03 — Mondai 3 No.21"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"いえから かいしゃまで １じかん（　）。",options:["たちます","いきます","かかります","します"],answer:2,explanation:"“Dari rumah ke kantor perlu waktu 1 jam.” かかります dipakai untuk menyatakan waktu yang diperlukan.",material:"Paket D03 — Mondai 3 No.22"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"ほんを たくさん いれましたから、かばんが とても（　）です。",options:["おもい","かるい","よわい","たかい"],answer:0,explanation:"Karena banyak buku dimasukkan, tasnya jadi sangat おもい (berat).",material:"Paket D03 — Mondai 3 No.23"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"ゆうこさんは あまり はなしません。（　）な ひとです。",options:["ひま","ふべん","にぎやか","しずか"],answer:3,explanation:"Yuko tidak banyak bicara, jadi ia orang yang しずか (pendiam/tenang).",material:"Paket D03 — Mondai 3 No.24"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"よごれた シャツを（　）しました。",options:["よしゅう","しつもん","せんたく","あいさつ"],answer:2,explanation:"Kemeja yang kotor di せんたく (dicuci).",material:"Paket D03 — Mondai 3 No.25"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"ともだちの いえに くるまが ３（　）あります。",options:["まい","だい","かい","こ"],answer:1,explanation:"Kata bantu bilangan untuk kendaraan/mesin adalah だい.",material:"Paket D03 — Mondai 3 No.26"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"かんじを（　）。おしえて ください。",options:["わすれました","おぼえました","のみました","しりました"],answer:0,explanation:"“Saya lupa kanjinya. Tolong ajari saya.” わすれました (lupa) paling sesuai dengan permintaan diajari.",material:"Paket D03 — Mondai 3 No.27"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"（　）ですね。でんきを つけましょう。",options:["せまい","くろい","くらい","うすい"],answer:2,explanation:"“Gelap ya. Ayo nyalakan lampu.” くらい berarti gelap.",material:"Paket D03 — Mondai 3 No.28"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"はじめまして。（　）よろしく おねがいします。",options:["どうも","どうぞ","とても","どんな"],answer:1,explanation:"Ungkapan baku perkenalan: はじめまして。どうぞ よろしく おねがいします。",material:"Paket D03 — Mondai 3 No.29"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"わからない ことばが ありましたから、（　）を みました。",options:["とけい","つくえ","えんぴつ","じしょ"],answer:3,explanation:"Karena ada kata yang tidak dimengerti, saya melihat じしょ (kamus).",material:"Paket D03 — Mondai 3 No.30"},
      {category:"Parafrasa",instruction:"＿＿＿の ぶんと だいたい おなじ いみの ぶんが あります。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"リーさんは いもうとが ひとりと おとうとが ふたり います。",options:["リーさんは ３にん きょうだいです。","リーさんは ４にん きょうだいです。","リーさんは ５にん きょうだいです。","リーさんは きょうだいの なかで いちばん わかいです。"],answer:1,explanation:"1 adik perempuan + 2 adik laki-laki + Lee sendiri = 4 orang bersaudara.",material:"Paket D03 — Mondai 4 No.31"},
      {category:"Parafrasa",instruction:"＿＿＿の ぶんと だいたい おなじ いみの ぶんが あります。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"きょうは しゅくだいが すくないです。",options:["きょうは しゅくだいが たくさん あります。","きょうは しゅくだいが あまり ありません。","きょうは しゅくだいが ありません。","きょうは しゅくだいが むずかしいです。"],answer:1,explanation:"すくない (sedikit) semakna dengan あまり ありません (tidak terlalu banyak).",material:"Paket D03 — Mondai 4 No.32"},
      {category:"Parafrasa",instruction:"＿＿＿の ぶんと だいたい おなじ いみの ぶんが あります。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"へやを そうじしました。",options:["へやを あかるく しました。","へやを きれいに しました。","へやを あたらしく しました。","へやを かわいく しました。"],answer:1,explanation:"そうじしました (membersihkan) semakna dengan membuat kamar きれいに (bersih).",material:"Paket D03 — Mondai 4 No.33"},
      {category:"Parafrasa",instruction:"＿＿＿の ぶんと だいたい おなじ いみの ぶんが あります。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"がっこうに ちこくしました。",options:["がっこうを やすみました。","がっこうから はやく かえりました。","がっこうに はやく いきました。","がっこうに おそく いきました。"],answer:3,explanation:"ちこくしました (terlambat) berarti pergi ke sekolah おそく (terlambat/telat).",material:"Paket D03 — Mondai 4 No.34"},
      {category:"Parafrasa",instruction:"＿＿＿の ぶんと だいたい おなじ いみの ぶんが あります。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"タンさんは シンさんに くにの しゃしんを みせました。",options:["タンさんは シンさんの くにで しゃしんを とりました。","タンさんは シンさんの くにの しゃしんを みました。","シンさんは タンさんの くにの しゃしんを みました。","シンさんは タンさんの くにで しゃしんを とりました。"],answer:2,explanation:"タンさんが みせた (memperlihatkan) berarti シンさんが みた (melihat) foto negara Tan.",material:"Paket D03 — Mondai 4 No.35"}
    ]
  }
};
/* Paket ujian per-5-bab yang disusun manual (bukan digenerate acak) -
   memakai hanya kosakata/kanji/pola kalimat yang sudah diajarkan di
   rentang bab tersebut, supaya soal benar-benar sesuai progres siswa.
   Baru Bab 1-5 yang sudah dibuat; rentang lain masih pakai generator
   acak (lihat buildSelectedQuestions) sampai dibuatkan manual juga. */
const curatedBabPackages={
  1:{
    questions:[
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"<u>私</u>は がくせいです。",options:["わたし","あなた","かれ","どなた"],answer:0,explanation:"私 dibaca “わたし” dan berarti saya.",material:"Bab 1–5 · Mondai 1 No.1",srsId:"kanji:私"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"あのかたは <u>会社員</u>です。",options:["かいしゃいん","ぎんこういん","けんきゅうしゃ","きょうし"],answer:0,explanation:"会社員 dibaca “かいしゃいん” dan berarti pegawai perusahaan.",material:"Bab 1–5 · Mondai 1 No.2",srsId:"kanji:会社員"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"わたしは <u>韓国</u>から きました。",options:["かんこく","ちゅうごく","にほん","だいがく"],answer:0,explanation:"韓国 dibaca “かんこく” dan berarti Korea.",material:"Bab 1–5 · Mondai 1 No.3",srsId:"kanji:韓国"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"これは わたしの <u>辞書</u>です。",options:["じしょ","ざっし","しんぶん","めいし"],answer:0,explanation:"辞書 dibaca “じしょ” dan berarti kamus.",material:"Bab 1–5 · Mondai 1 No.4",srsId:"kanji:辞書"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"その <u>新聞</u>は わたしのです。",options:["しんぶん","ざっし","てちょう","めいし"],answer:0,explanation:"新聞 dibaca “しんぶん” dan berarti koran.",material:"Bab 1–5 · Mondai 1 No.5",srsId:"kanji:新聞"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"<u>会議室</u>は あそこです。",options:["かいぎしつ","じむしょ","きょうしつ","しょくどう"],answer:0,explanation:"会議室 dibaca “かいぎしつ” dan berarti ruang rapat.",material:"Bab 1–5 · Mondai 1 No.6",srsId:"kanji:会議室"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"エレベーターは <u>何階</u>ですか。",options:["なんがい","なんかい","なんえん","なんにち"],answer:0,explanation:"何階 dibaca “なんがい” dan berarti lantai berapa.",material:"Bab 1–5 · Mondai 1 No.7",srsId:"kanji:何階"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"まいあさ 6じに <u>起きます</u>。",options:["おきます","ねます","はたらきます","やすみます"],answer:0,explanation:"起きます dibaca “おきます” dan berarti bangun tidur.",material:"Bab 1–5 · Mondai 1 No.8",srsId:"kanji:起きます"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"きょうは <u>何曜日</u>ですか。",options:["なんようび","なんじ","なんにち","なんがつ"],answer:0,explanation:"何曜日 dibaca “なんようび” dan berarti hari apa.",material:"Bab 1–5 · Mondai 1 No.9",srsId:"kanji:何曜日"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"<u>午後</u>は かいぎです。",options:["ごご","ごぜん","いま","まいにち"],answer:0,explanation:"午後 dibaca “ごご” dan berarti sore/siang setelah jam 12.",material:"Bab 1–5 · Mondai 1 No.10",srsId:"kanji:午後"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"<u>友達</u>と がっこうへ いきます。",options:["ともだち","かぞく","かれ","ひと"],answer:0,explanation:"友達 dibaca “ともだち” dan berarti teman.",material:"Bab 1–5 · Mondai 1 No.11",srsId:"kanji:友達"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"<u>来週</u> にほんへ いきます。",options:["らいしゅう","せんしゅう","こんしゅう","らいねん"],answer:0,explanation:"来週 dibaca “らいしゅう” dan berarti minggu depan.",material:"Bab 1–5 · Mondai 1 No.12",srsId:"kanji:来週"},
      {category:"Penulisan Kanji",instruction:"＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"あの <u>がくせい</u>は わたしの ともだちです。",options:["学生","先生","医者","会社員"],answer:0,explanation:"がくせい ditulis 学生, berarti pelajar/mahasiswa.",material:"Bab 1–5 · Mondai 2 No.13",srsId:"kanji:学生"},
      {category:"Penulisan Kanji",instruction:"＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"これは わたしの <u>とけい</u>です。",options:["時計","眼鏡","傘","鞄"],answer:0,explanation:"とけい ditulis 時計, berarti jam/arloji.",material:"Bab 1–5 · Mondai 2 No.14",srsId:"kanji:時計"},
      {category:"Penulisan Kanji",instruction:"＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"その <u>えんぴつ</u>は だれのですか。",options:["鉛筆","雑誌","手帳","名刺"],answer:0,explanation:"えんぴつ ditulis 鉛筆, berarti pensil.",material:"Bab 1–5 · Mondai 2 No.15",srsId:"kanji:鉛筆"},
      {category:"Penulisan Kanji",instruction:"＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"<u>かいしゃ</u>は どこですか。",options:["会社","事務所","教室","食堂"],answer:0,explanation:"かいしゃ ditulis 会社, berarti perusahaan.",material:"Bab 1–5 · Mondai 2 No.16",srsId:"kanji:会社"},
      {category:"Penulisan Kanji",instruction:"＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"まいあさ 7じに <u>おきます</u>。",options:["起きます","寝ます","働きます","終わります"],answer:0,explanation:"おきます ditulis 起きます, berarti bangun tidur.",material:"Bab 1–5 · Mondai 2 No.17",srsId:"kanji:起きます"},
      {category:"Penulisan Kanji",instruction:"＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"<u>にちようび</u>は やすみです。",options:["日曜日","土曜日","月曜日","金曜日"],answer:0,explanation:"にちようび ditulis 日曜日, berarti hari Minggu.",material:"Bab 1–5 · Mondai 2 No.18",srsId:"kanji:日曜日"},
      {category:"Penulisan Kanji",instruction:"＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"わたしは <u>でんしゃ</u>で がっこうへ いきます。",options:["電車","自転車","飛行機","地下鉄"],answer:0,explanation:"でんしゃ ditulis 電車, berarti kereta listrik.",material:"Bab 1–5 · Mondai 2 No.19",srsId:"kanji:電車"},
      {category:"Penulisan Kanji",instruction:"＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"<u>おてあらい</u>は どこですか。",options:["お手洗い","事務所","教室","食堂"],answer:0,explanation:"おてあらい ditulis お手洗い, berarti kamar kecil/WC.",material:"Bab 1–5 · Mondai 2 No.20",srsId:"kanji:お手洗い"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"わたしは がくせい（　）。",options:["です","じゃありません","か","の"],answer:0,explanation:"Pola N1は N2です dipakai untuk pernyataan positif: “Saya adalah pelajar.”",material:"Bab 1–5 · Mondai 3 No.21",srsId:"materi:book1:0:0"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"あのかたは せんせい（　）。がくせいです。",options:["じゃありません","です","ですか","の"],answer:0,explanation:"じゃありません adalah bentuk negatif dari です: “Bukan guru, [tapi] pelajar.”",material:"Bab 1–5 · Mondai 3 No.22",srsId:"materi:book1:0:0"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"これは わたし（　）ほんです。",options:["の","も","は","か"],answer:0,explanation:"の menghubungkan dua kata benda untuk kepemilikan: “buku saya.”",material:"Bab 1–5 · Mondai 3 No.23",srsId:"materi:book1:1:0"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"わたしは がくせいです。あなた（　）ですか。",options:["も","の","を","で"],answer:0,explanation:"も berarti “juga”, menggantikan は pada topik kedua.",material:"Bab 1–5 · Mondai 3 No.24",srsId:"materi:book1:1:0"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"かいぎしつは（　）ですか。",options:["どこ","だれ","いつ","なに"],answer:0,explanation:"どこ dipakai untuk menanyakan tempat.",material:"Bab 1–5 · Mondai 3 No.25",srsId:"materi:book1:2:0"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"「これは あなたの かさですか。」「いいえ、（　）。」",options:["ちがいます","そうです","どうも","どうぞ"],answer:0,explanation:"ちがいます dipakai untuk menyangkal informasi yang salah.",material:"Bab 1–5 · Mondai 3 No.26",srsId:"materi:book1:2:0"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"わたしは まいあさ 6じ（　）おきます。",options:["に","で","と","へ"],answer:0,explanation:"に menandai waktu yang spesifik seperti jam.",material:"Bab 1–5 · Mondai 3 No.27",srsId:"materi:book1:3:0"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"げつようび（　）きんようびまで はたらきます。",options:["から","まで","と","に"],answer:0,explanation:"から menunjukkan titik mulai, dipasangkan dengan まで.",material:"Bab 1–5 · Mondai 3 No.28",srsId:"materi:book1:3:0"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"わたしは でんしゃ（　）がっこうへ いきます。",options:["で","へ","と","に"],answer:0,explanation:"で menandai alat transportasi yang dipakai.",material:"Bab 1–5 · Mondai 3 No.29",srsId:"materi:book1:4:0"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"ともだち（　）かえります。",options:["と","へ","で","の"],answer:0,explanation:"と menunjukkan teman yang menyertai suatu kegiatan.",material:"Bab 1–5 · Mondai 3 No.30",srsId:"materi:book1:4:0"},
      {category:"Parafrasa",instruction:"＿＿＿の ぶんと だいたい おなじ いみの ぶんが あります。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"あのかたは せんせいです。",options:["あのかたは がくせいです。","あのかたは きょうしです。","あのかたは いしゃです。","あのかたは かいしゃいんです。"],answer:1,explanation:"せんせい dan きょうし sama-sama berarti “guru”, meski きょうし lebih sering dipakai untuk menyebut profesi sendiri.",material:"Bab 1–5 · Mondai 4 No.31",srsId:"materi:book1:0:0"},
      {category:"Parafrasa",instruction:"＿＿＿の ぶんと だいたい おなじ いみの ぶんが あります。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"これは わたしの ほんです。",options:["この ほんは わたしのです。","その ほんは あなたのです。","あの ほんは せんせいのです。","これは あなたの ほんです。"],answer:0,explanation:"これは Nです dapat diubah menjadi この Nは……のです, karena これ menggantikan “ini+benda” sedangkan この menerangkan benda yang disebut.",material:"Bab 1–5 · Mondai 4 No.32",srsId:"materi:book1:1:0"},
      {category:"Parafrasa",instruction:"＿＿＿の ぶんと だいたい おなじ いみの ぶんが あります。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"かいぎしつは どこですか。",options:["かいぎしつは どちらですか。","かいぎしつは なんですか。","かいぎしつは だれですか。","かいぎしつは いつですか。"],answer:0,explanation:"どこ dan どちら sama-sama menanyakan tempat; どちら lebih sopan.",material:"Bab 1–5 · Mondai 4 No.33",srsId:"materi:book1:2:0"},
      {category:"Parafrasa",instruction:"＿＿＿の ぶんと だいたい おなじ いみの ぶんが あります。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"きょうは やすみです。",options:["きょうは はたらきます。","きょうは はたらきません。","きょうは べんきょうします。","きょうは おわります。"],answer:1,explanation:"やすみ (hari libur) berarti tidak bekerja, jadi はたらきません paling sesuai.",material:"Bab 1–5 · Mondai 4 No.34",srsId:"materi:book1:3:0"},
      {category:"Parafrasa",instruction:"＿＿＿の ぶんと だいたい おなじ いみの ぶんが あります。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"わたしは ひとりで がっこうへ いきます。",options:["わたしは ともだちと がっこうへ いきます。","わたしは かぞくと がっこうへ いきます。","わたしは だれとも がっこうへ いきません。","わたしは ともだちと かえります。"],answer:2,explanation:"ひとりで (sendirian) berarti tidak pergi bersama siapa pun, sepadan dengan だれとも～ません.",material:"Bab 1–5 · Mondai 4 No.35",srsId:"materi:book1:4:0"}
    ]
  },
  6:{
    questions:[
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"あさごはんに <u>卵</u>を たべます。",options:["たまご","にく","さかな","やさい"],answer:0,explanation:"卵 dibaca “たまご” dan berarti telur.",material:"Bab 6–10 · Mondai 1 No.1",srsId:"kanji:卵"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"はこの <u>上</u>に ねこが います。",options:["うえ","した","なか","そと"],answer:0,explanation:"上 dibaca “うえ” dan berarti atas.",material:"Bab 6–10 · Mondai 1 No.2",srsId:"kanji:上"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"ははに <u>手紙</u>を かきます。",options:["てがみ","しゃしん","きっぷ","にもつ"],answer:0,explanation:"手紙 dibaca “てがみ” dan berarti surat.",material:"Bab 6–10 · Mondai 1 No.3",srsId:"kanji:手紙"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"<u>父</u>は かいしゃいんです。",options:["ちち","はは","あに","あね"],answer:0,explanation:"父 dibaca “ちち” dan berarti ayah (dipakai untuk menyebut ayah sendiri).",material:"Bab 6–10 · Mondai 1 No.4",srsId:"kanji:父"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"わたしは ちちに てがみを <u>送ります</u>。",options:["おくります","かします","かります","おしえます"],answer:0,explanation:"送ります dibaca “おくります” dan berarti mengirim.",material:"Bab 6–10 · Mondai 1 No.5",srsId:"kanji:送ります"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"<u>妹</u>は がくせいです。",options:["いもうと","あね","むすめ","はは"],answer:0,explanation:"妹 dibaca “いもうと” dan berarti adik perempuan.",material:"Bab 6–10 · Mondai 1 No.6",srsId:"kanji:妹"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"このまちは とても <u>有名</u>です。",options:["ゆうめい","げんき","べんり","しんせつ"],answer:0,explanation:"有名 dibaca “ゆうめい” dan berarti terkenal.",material:"Bab 6–10 · Mondai 1 No.7",srsId:"kanji:有名"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"<u>新しい</u> れいぞうこを かいました。",options:["あたらしい","ふるい","おおきい","ちいさい"],answer:0,explanation:"新しい dibaca “あたらしい” dan berarti baru.",material:"Bab 6–10 · Mondai 1 No.8",srsId:"kanji:新しい"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"ふゆは とても <u>寒い</u>です。",options:["さむい","あつい","つめたい","わるい"],answer:0,explanation:"寒い dibaca “さむい” dan berarti dingin (cuaca/suhu).",material:"Bab 6–10 · Mondai 1 No.9",srsId:"kanji:寒い"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"わたしは <u>音楽</u>が すきです。",options:["おんがく","りょうり","りょこう","やきゅう"],answer:0,explanation:"音楽 dibaca “おんがく” dan berarti musik.",material:"Bab 6–10 · Mondai 1 No.10",srsId:"kanji:音楽"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"この <u>漢字</u>が わかりません。",options:["かんじ","じ","え","うた"],answer:0,explanation:"漢字 dibaca “かんじ” dan berarti aksara kanji.",material:"Bab 6–10 · Mondai 1 No.11",srsId:"kanji:漢字"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"<u>犬</u>が こうえんに います。",options:["いぬ","ねこ","き","はこ"],answer:0,explanation:"犬 dibaca “いぬ” dan berarti anjing.",material:"Bab 6–10 · Mondai 1 No.12",srsId:"kanji:犬"},
      {category:"Penulisan Kanji",instruction:"＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"まいあさ おちゃを <u>のみます</u>。",options:["飲みます","食べます","吸います","買います"],answer:0,explanation:"のみます ditulis 飲みます, berarti minum.",material:"Bab 6–10 · Mondai 2 No.13",srsId:"kanji:飲みます"},
      {category:"Penulisan Kanji",instruction:"＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"りょこうの <u>しゃしん</u>を とります。",options:["写真","手紙","宿題","年賀状"],answer:0,explanation:"しゃしん ditulis 写真, berarti foto.",material:"Bab 6–10 · Mondai 2 No.14",srsId:"kanji:写真"},
      {category:"Penulisan Kanji",instruction:"＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"<u>はは</u>は せんせいです。",options:["母","父","姉","兄"],answer:0,explanation:"はは ditulis 母, berarti ibu (dipakai untuk menyebut ibu sendiri).",material:"Bab 6–10 · Mondai 2 No.15",srsId:"kanji:母"},
      {category:"Penulisan Kanji",instruction:"＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"としょかんで ほんを <u>かります</u>。",options:["借ります","貸します","教えます","習います"],answer:0,explanation:"かります ditulis 借ります, berarti meminjam.",material:"Bab 6–10 · Mondai 2 No.16",srsId:"kanji:借ります"},
      {category:"Penulisan Kanji",instruction:"＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"このでんしゃは とても <u>べんり</u>です。",options:["便利","有名","元気","大きい"],answer:0,explanation:"べんり ditulis 便利, berarti praktis.",material:"Bab 6–10 · Mondai 2 No.17",srsId:"kanji:便利"},
      {category:"Penulisan Kanji",instruction:"＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"この <u>りょうり</u>が すきです。",options:["料理","音楽","野球","旅行"],answer:0,explanation:"りょうり ditulis 料理, berarti masakan.",material:"Bab 6–10 · Mondai 2 No.18",srsId:"kanji:料理"},
      {category:"Penulisan Kanji",instruction:"＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"<u>まど</u>は そこです。",options:["窓","箱","棚","木"],answer:0,explanation:"まど ditulis 窓, berarti jendela.",material:"Bab 6–10 · Mondai 2 No.19",srsId:"kanji:窓"},
      {category:"Penulisan Kanji",instruction:"＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"こうえんの <u>ちかく</u>に みせが あります。",options:["近く","隣","間","中"],answer:0,explanation:"ちかく ditulis 近く, berarti dekat.",material:"Bab 6–10 · Mondai 2 No.20",srsId:"kanji:近く"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"まいあさ おちゃ（　）のみます。",options:["を","に","で","と"],answer:0,explanation:"を menandai objek yang dikenai tindakan, seperti minuman yang diminum.",material:"Bab 6–10 · Mondai 3 No.21",srsId:"materi:book1:5:0"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"レストラン（　）ひるごはんを たべます。",options:["で","に","を","と"],answer:0,explanation:"で menandai tempat kegiatan berlangsung.",material:"Bab 6–10 · Mondai 3 No.22",srsId:"materi:book1:5:0"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"わたしは ともだち（　）プレゼントを あげます。",options:["に","を","で","と"],answer:0,explanation:"に menandai penerima dalam pola memberi.",material:"Bab 6–10 · Mondai 3 No.23",srsId:"materi:book1:6:0"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"わたしは ちち（　）とけいを もらいます。",options:["に","を","で","と"],answer:0,explanation:"に menandai sumber dalam pola menerima (もらいます).",material:"Bab 6–10 · Mondai 3 No.24",srsId:"materi:book1:6:0"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"このまちは あまり にぎやか（　）。",options:["じゃありません","です","くないです","の"],answer:0,explanation:"な形容詞 (na-keiyoushi) memakai じゃありません untuk bentuk negatif, berbeda dari い形容詞 yang memakai くないです.",material:"Bab 6–10 · Mondai 3 No.25",srsId:"materi:book1:7:0"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"でんしゃは バス（　）はやいです。",options:["より","と","に","で"],answer:0,explanation:"より dipakai untuk membandingkan dua hal.",material:"Bab 6–10 · Mondai 3 No.26",srsId:"materi:book1:7:0"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"わたしは やきゅう（　）すきです。",options:["が","を","に","で"],answer:0,explanation:"すき dipakai dengan partikel が untuk menandai hal yang disukai.",material:"Bab 6–10 · Mondai 3 No.27",srsId:"materi:book1:8:0"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"わたしは かんじが（　）わかりません。",options:["ぜんぜん","とても","あまり","だいたい"],answer:0,explanation:"ぜんぜん dipakai bersama bentuk negatif untuk menyatakan “sama sekali tidak”.",material:"Bab 6–10 · Mondai 3 No.28",srsId:"materi:book1:8:0"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"こうえんに こどもが（　）。",options:["います","あります","です","ちがいます"],answer:0,explanation:"います dipakai untuk keberadaan manusia dan hewan.",material:"Bab 6–10 · Mondai 3 No.29",srsId:"materi:book1:9:0"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"つくえの うえに ほんが（　）。",options:["あります","います","です","ちがいます"],answer:0,explanation:"あります dipakai untuk keberadaan benda mati.",material:"Bab 6–10 · Mondai 3 No.30",srsId:"materi:book1:9:0"},
      {category:"Parafrasa",instruction:"＿＿＿の ぶんと だいたい おなじ いみの ぶんが あります。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"あさごはんに パンを たべます。",options:["あさ パンを たべます。","ばん パンを たべます。","ひる パンを のみます。","あさ おちゃを のみます。"],answer:0,explanation:"あさごはんに たべます berarti makan di waktu あさ (pagi).",material:"Bab 6–10 · Mondai 4 No.31",srsId:"materi:book1:5:0"},
      {category:"Parafrasa",instruction:"＿＿＿の ぶんと だいたい おなじ いみの ぶんが あります。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"わたしは ちちに とけいを もらいました。",options:["ちちは わたしに とけいを あげました。","わたしは ちちに とけいを あげました。","ちちは わたしに とけいを かりました。","わたしは ちちから とけいを かしました。"],answer:0,explanation:"“Saya menerima jam dari ayah” sama artinya dengan “Ayah memberi saya jam” — もらいます dan あげます berganti sudut pandang pelaku.",material:"Bab 6–10 · Mondai 4 No.32",srsId:"materi:book1:6:0"},
      {category:"Parafrasa",instruction:"＿＿＿の ぶんと だいたい おなじ いみの ぶんが あります。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"このしごとは あまり むずかしくないです。",options:["このしごとは やさしいです。","このしごとは むずかしいです。","このしごとは たかいです。","このしごとは いそがしいです。"],answer:0,explanation:"あまり むずかしくない (tidak terlalu sulit) hampir sama artinya dengan やさしい (mudah).",material:"Bab 6–10 · Mondai 4 No.33",srsId:"materi:book1:7:0"},
      {category:"Parafrasa",instruction:"＿＿＿の ぶんと だいたい おなじ いみの ぶんが あります。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"わたしは にほんごが あまり じょうずじゃありません。",options:["わたしは にほんごが じょうずです。","わたしは にほんごが へたです。","わたしは にほんごが すきです。","わたしは にほんごが きらいです。"],answer:1,explanation:"あまり じょうずじゃありません (kurang begitu pandai) semakna dengan へたです (tidak pandai).",material:"Bab 6–10 · Mondai 4 No.34",srsId:"materi:book1:8:0"},
      {category:"Parafrasa",instruction:"＿＿＿の ぶんと だいたい おなじ いみの ぶんが あります。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"つくえの したに ねこが います。",options:["ねこは つくえの したに います。","ねこは つくえの うえに います。","つくえは ねこの したに あります。","つくえは ねこの うえに あります。"],answer:0,explanation:"場所に Nが います (menekankan apa yang ada) dapat diubah menjadi Nは 場所に います (menekankan lokasi benda/makhluk yang sudah diketahui) tanpa mengubah fakta.",material:"Bab 6–10 · Mondai 4 No.35",srsId:"materi:book1:9:0"}
    ]
  },
  11:{
    questions:[
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"ゆうびんきょくで <u>切手</u>を かいます。",options:["きって","ふうとう","はがき","きっぷ"],answer:0,explanation:"切手 dibaca “きって” dan berarti perangko.",material:"Bab 11–15 · Mondai 1 No.1",srsId:"kanji:切手"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"としょかんに <u>留学生</u>が います。",options:["りゅうがくせい","いしゃ","せんせい","がくせい"],answer:0,explanation:"留学生 dibaca “りゅうがくせい” dan berarti pelajar asing.",material:"Bab 11–15 · Mondai 1 No.2",srsId:"kanji:留学生"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"あきは <u>涼しい</u>です。",options:["すずしい","あたたかい","さむい","あつい"],answer:0,explanation:"涼しい dibaca “すずしい” dan berarti sejuk.",material:"Bab 11–15 · Mondai 1 No.3",srsId:"kanji:涼しい"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"この カレーは とても <u>辛い</u>です。",options:["からい","あまい","おもい","かるい"],answer:0,explanation:"辛い dibaca “からい” dan berarti pedas.",material:"Bab 11–15 · Mondai 1 No.4",srsId:"kanji:辛い"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"きょうは <u>雨</u>です。",options:["あめ","ゆき","くもり","てんき"],answer:0,explanation:"雨 dibaca “あめ” dan berarti hujan.",material:"Bab 11–15 · Mondai 1 No.5",srsId:"kanji:雨"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"こどもと こうえんで <u>遊びます</u>。",options:["あそびます","つかれます","けっこんします","しょくじします"],answer:0,explanation:"遊びます dibaca “あそびます” dan berarti bermain.",material:"Bab 11–15 · Mondai 1 No.6",srsId:"kanji:遊びます"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"にちようびに ともだちと <u>泳ぎます</u>。",options:["およぎます","あそびます","つかれます","けっこんします"],answer:0,explanation:"泳ぎます dibaca “およぎます” dan berarti berenang.",material:"Bab 11–15 · Mondai 1 No.7",srsId:"kanji:泳ぎます"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"でんきを <u>消します</u>。",options:["けします","つけます","あけます","しめます"],answer:0,explanation:"消します dibaca “けします” dan berarti mematikan.",material:"Bab 11–15 · Mondai 1 No.8",srsId:"kanji:消します"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"まどを <u>開けます</u>。",options:["あけます","しめます","けします","つけます"],answer:0,explanation:"開けます dibaca “あけます” dan berarti membuka.",material:"Bab 11–15 · Mondai 1 No.9",srsId:"kanji:開けます"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"この まちに <u>住みます</u>。",options:["すみます","つくります","うります","しります"],answer:0,explanation:"住みます dibaca “すみます” dan berarti tinggal.",material:"Bab 11–15 · Mondai 1 No.10",srsId:"kanji:住みます"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"<u>医者</u>は びょういんで はたらきます。",options:["いしゃ","かんごし","きょうし","けいさつかん"],answer:0,explanation:"医者 dibaca “いしゃ” dan berarti dokter.",material:"Bab 11–15 · Mondai 1 No.11",srsId:"kanji:医者"},
      {category:"Cara Baca Kanji",instruction:"＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"あには <u>会社員</u>です。",options:["かいしゃいん","こうむいん","てんいん","うんてんしゅ"],answer:0,explanation:"会社員 dibaca “かいしゃいん” dan berarti pegawai perusahaan.",material:"Bab 11–15 · Mondai 1 No.12",srsId:"kanji:会社員"},
      {category:"Penulisan Kanji",instruction:"＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"きってを 2<u>まい</u> ください。",options:["枚","台","回","人"],answer:0,explanation:"まい ditulis 枚, kata bantu bilangan untuk benda tipis seperti kertas.",material:"Bab 11–15 · Mondai 2 No.13",srsId:"kanji:枚"},
      {category:"Penulisan Kanji",instruction:"＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"デパートで <u>ぎゅうどん</u>を たべます。",options:["牛どん","天どん","焼肉","紅茶"],answer:0,explanation:"ぎゅうどん ditulis 牛どん, semangkuk nasi dengan daging sapi.",material:"Bab 11–15 · Mondai 2 No.14",srsId:"kanji:牛どん"},
      {category:"Penulisan Kanji",instruction:"＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"きょうは <u>あめ</u>です。",options:["雨","雪","曇り","天気"],answer:0,explanation:"あめ ditulis 雨, berarti hujan.",material:"Bab 11–15 · Mondai 2 No.15",srsId:"kanji:雨"},
      {category:"Penulisan Kanji",instruction:"＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"<u>せかい</u>には たくさん くにが あります。",options:["世界","季節","名所","海"],answer:0,explanation:"せかい ditulis 世界, berarti dunia.",material:"Bab 11–15 · Mondai 2 No.16",srsId:"kanji:世界"},
      {category:"Penulisan Kanji",instruction:"＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"しゅうまつに <u>つり</u>を します。",options:["釣り","散歩","買い物","食事"],answer:0,explanation:"つり ditulis 釣り, berarti memancing.",material:"Bab 11–15 · Mondai 2 No.17",srsId:"kanji:釣り"},
      {category:"Penulisan Kanji",instruction:"＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"でんしゃの <u>でぐち</u>は あちらです。",options:["出口","入口","南口","北口"],answer:0,explanation:"でぐち ditulis 出口, berarti pintu keluar.",material:"Bab 11–15 · Mondai 2 No.18",srsId:"kanji:出口"},
      {category:"Penulisan Kanji",instruction:"＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"この <u>ちず</u>を みて ください。",options:["地図","問題","答え","名前"],answer:0,explanation:"ちず ditulis 地図, berarti peta.",material:"Bab 11–15 · Mondai 2 No.19",srsId:"kanji:地図"},
      {category:"Penulisan Kanji",instruction:"＿＿＿の ことばは かんじで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"あには <u>けいさつかん</u>です。",options:["警察官","外交官","政治家","運転手"],answer:0,explanation:"けいさつかん ditulis 警察官, berarti polisi.",material:"Bab 11–15 · Mondai 2 No.20",srsId:"kanji:警察官"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"いっしゅうかんに に（　）およぎます。",options:["かい","にん","まい","だい"],answer:0,explanation:"回 dipakai untuk menyatakan frekuensi, misalnya berapa kali dalam seminggu.",material:"Bab 11–15 · Mondai 3 No.21",srsId:"materi:book1:10:0"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"「にほんに どのくらい いましたか。」「3ねん（　）いました。」",options:["ぐらい","と","も","で"],answer:0,explanation:"ぐらい dipakai untuk menyatakan perkiraan jumlah atau lama waktu.",material:"Bab 11–15 · Mondai 3 No.22",srsId:"materi:book1:10:0"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"きのうは とても げんき（　）。",options:["でした","です","でしょう","でしょうか"],answer:0,explanation:"な形容詞 (na-keiyoushi) memakai でした untuk bentuk lampau positif.",material:"Bab 11–15 · Mondai 3 No.23",srsId:"materi:book1:11:0"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"きのうは とても（　）。",options:["あつかったです","あついです","あつくないです","あつかったですか"],answer:0,explanation:"い形容詞 (i-keiyoushi) mengubah い menjadi かったです untuk bentuk lampau positif.",material:"Bab 11–15 · Mondai 3 No.24",srsId:"materi:book1:11:0"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"わたしは あたらしい くるまが（　）。",options:["ほしいです","すきです","あります","います"],answer:0,explanation:"Nが ほしいです menyatakan benda yang diinginkan.",material:"Bab 11–15 · Mondai 3 No.25",srsId:"materi:book1:12:0"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"にほんへ りょこうに（　）です。",options:["いきたい","いきます","いきません","いきました"],answer:0,explanation:"Vます-stem に たいです menyatakan keinginan melakukan tindakan.",material:"Bab 11–15 · Mondai 3 No.26",srsId:"materi:book1:12:0"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"ちずを（　）ください。",options:["みせて","みせます","みせました","みせない"],answer:0,explanation:"Vて ください dipakai untuk meminta tindakan dengan sopan.",material:"Bab 11–15 · Mondai 3 No.27",srsId:"materi:book1:13:0"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"いま でんわで はなして（　）。",options:["います","あります","です","ちがいます"],answer:0,explanation:"Vて います menyatakan kegiatan yang sedang berlangsung.",material:"Bab 11–15 · Mondai 3 No.28",srsId:"materi:book1:13:0"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"ここで しゃしんを とっても（　）か。",options:["いいです","わるいです","だめです","いけません"],answer:0,explanation:"Vても いいですか dipakai untuk meminta izin.",material:"Bab 11–15 · Mondai 3 No.29",srsId:"materi:book1:14:0"},
      {category:"Kosakata",instruction:"（　）に なにを いれますか。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"ここで たばこを すって（　）。",options:["はいけません","もいいです","ください","います"],answer:0,explanation:"Vては いけません menyatakan larangan.",material:"Bab 11–15 · Mondai 3 No.30",srsId:"materi:book1:14:0"},
      {category:"Parafrasa",instruction:"＿＿＿の ぶんと だいたい おなじ いみの ぶんが あります。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"にほんごを 2ねんかん べんきょうしました。",options:["にほんごの べんきょうは 2ねんかんでした。","にほんごの べんきょうは 2かいでした。","にほんごを 2かい べんきょうしました。","にほんごを 2にん べんきょうしました。"],answer:0,explanation:"Kalimat menyatakan hal yang sama, hanya dengan べんきょう sebagai topik.",material:"Bab 11–15 · Mondai 4 No.31",srsId:"materi:book1:10:0"},
      {category:"Parafrasa",instruction:"＿＿＿の ぶんと だいたい おなじ いみの ぶんが あります。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"きょうは きのうより さむいです。",options:["きのうは きょうより あたたかかったです。","きのうは きょうより さむかったです。","きょうは きのうと おなじ さむさです。","きのうは きょうより あついです。"],answer:0,explanation:"“Hari ini lebih dingin dari kemarin” berarti kemarin lebih hangat (あたたかかったです) daripada hari ini.",material:"Bab 11–15 · Mondai 4 No.32",srsId:"materi:book1:11:0"},
      {category:"Parafrasa",instruction:"＿＿＿の ぶんと だいたい おなじ いみの ぶんが あります。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"わたしは あたらしい かばんが ほしいです。",options:["わたしは あたらしい かばんを かいたいです。","わたしは あたらしい かばんを うりたいです。","わたしは ふるい かばんが ほしいです。","わたしは かばんが きらいです。"],answer:0,explanation:"ほしいです (ingin memiliki) dekat maknanya dengan かいたいです (ingin membeli) untuk benda yang belum dimiliki.",material:"Bab 11–15 · Mondai 4 No.33",srsId:"materi:book1:12:0"},
      {category:"Parafrasa",instruction:"＿＿＿の ぶんと だいたい おなじ いみの ぶんが あります。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"あにが へやに はいりました。",options:["あには いま へやの なかに います。","あには いま へやの そとに います。","あには いま へやから でました。","あには いま へやを でます。"],answer:0,explanation:"はいりました (masuk) berarti sekarang berada di dalam (なかに います).",material:"Bab 11–15 · Mondai 4 No.34",srsId:"materi:book1:13:0"},
      {category:"Parafrasa",instruction:"＿＿＿の ぶんと だいたい おなじ いみの ぶんが あります。1・2・3・4から いちばん いい ものを ひとつ えらんでください。",html:"あには けいさつかんです。",options:["あには けいさつしょで はたらいています。","あには びょういんで はたらいています。","あには がっこうで はたらいています。","あには ぎんこうで はたらいています。"],answer:0,explanation:"けいさつかん (polisi) biasanya bekerja di けいさつしょ (kantor polisi).",material:"Bab 11–15 · Mondai 4 No.35",srsId:"materi:book1:14:0"}
    ]
  }
};

const $=id=>document.getElementById(id);
const testTypeLabels={vocabulary:"Kosakata",kanji:"Kanji",grammar:"Tata Bahasa",sentence:"Susunan Kalimat",reading:"Bacaan",audio:"Audio",situational:"Situasional"};
let questions=[...defaultQuestions],testType="vocabulary",rangeStart=1,mockPackage="",current=0,mode="simulation",answers=Array(questions.length).fill(null),checked=Array(questions.length).fill(false),flags=Array(questions.length).fill(false),furigana=true,timerId=null,seconds=720,reviewOnly=false,reviewIndexes=[];
function shuffled(values){return [...values].sort(()=>Math.random()-.5)}
function collectRangeData(source){const rows=[];for(let bab=rangeStart;bab<rangeStart+5;bab++)(source[bab]||[]).forEach(item=>rows.push({item,bab}));return rows}
function optionSet(correct,pool){return shuffled([correct,...shuffled(pool.filter(value=>value&&value!==correct)).slice(0,3)])}
/* bab 1-25 = Buku 1 (lessonIndex 0-24), bab 26-50 = Buku 2 (lessonIndex
   0-24) - penomoran bab di data ini SAMA dengan penomoran Pelajaran di
   Materi Pelajaran, jadi soal bisa dipetakan balik ke item SRS yang
   sudah dipakai flashcard/materi (lihat srsId di tiap builder di bawah). */
function materiIdForBab(bab){return `materi:book${bab<=25?1:2}:${bab<=25?bab-1:bab-26}:0`}
function vocabularyQuestions(){const source=collectRangeData(babKosakataData),rows=shuffled(source).slice(0,10),meanings=source.map(row=>row.item[1]);return rows.map(({item,bab})=>{const options=optionSet(item[1],meanings);return{category:"Kosakata",instruction:"Pilih arti kosakata yang paling tepat.",html:item[0],options,answer:options.indexOf(item[1]),explanation:`${item[0]} berarti “${item[1]}”. Kosakata ini berasal dari Bab ${bab}.`,material:`Bab ${bab} · Kosakata`,srsId:`hafalan:bab${bab}:${item[0]}`}})}
function kanjiQuestions(){const source=collectRangeData(babKanjiData),rows=shuffled(source).slice(0,10),readings=source.map(row=>row.item[1]);return rows.map(({item,bab})=>{const options=optionSet(item[1],readings);return{category:"Kanji",instruction:"Pilih cara baca kanji yang benar.",html:`<ruby>${item[0]}<rt>${item[1]}</rt></ruby>`,options,answer:options.indexOf(item[1]),explanation:`${item[0]} dibaca ${item[1]} dan berarti “${item[2]}”.`,material:`Bab ${bab} · Kanji dan cara baca`,srsId:`kanji:${item[0]}`}})}
function grammarQuestions(){const result=[];for(let bab=rangeStart;bab<rangeStart+5;bab++){const item=tailoredQuizData[bab];if(item)result.push({category:"Tata Bahasa",instruction:`Pilih jawaban yang sesuai dengan pola Bab ${bab}.`,html:item[0],options:item[1],answer:item[2],explanation:item[3],material:`Bab ${bab} · Tata bahasa`,srsId:materiIdForBab(bab)})}return result}
function contextualQuestions(kind){const source=collectRangeData(babKanjiData),rows=shuffled(source).slice(0,10),allWords=source.map(row=>row.item[0]),allMeanings=source.map(row=>row.item[2]);return rows.map(({item,bab})=>{const [word,reading,meaning]=item;
  if(kind==="sentence"){const correct=`${word}を おぼえます。`,options=optionSet(correct,[`${word}が おぼえます。`,`${word}へ おぼえます。`,`おぼえます ${word}を。`]);return{category:"Susunan Kalimat",instruction:"Pilih susunan kalimat yang paling tepat.",html:`“Saya menghafalkan ${meaning}.”`,options,answer:options.indexOf(correct),explanation:`Objek ditandai を dan diletakkan sebelum kata kerja: ${correct}`,material:`Bab ${bab} · Kosakata dalam kalimat`,srsId:`kanji:${word}`}}
  if(kind==="reading"){const options=optionSet(meaning,allMeanings);return{category:"Bacaan",instruction:"Baca kalimat pendek, lalu pilih maknanya.",html:`これは <ruby>${word}<rt>${reading}</rt></ruby> です。`,options,answer:options.indexOf(meaning),explanation:`Kata ${word} (${reading}) pada teks berarti “${meaning}”.`,material:`Bab ${bab} · Bacaan pendek`,srsId:`kanji:${word}`}}
  if(kind==="audio"){const options=optionSet(word,allWords);return{category:"Audio",instruction:"Dengarkan audio, lalu pilih kata yang diucapkan.",html:"音声を聞いてください。",audio:reading,options,answer:options.indexOf(word),explanation:`Audio mengucapkan ${reading}, yaitu ${word} yang berarti “${meaning}”.`,material:`Bab ${bab} · Pemahaman audio`,srsId:`kanji:${word}`}}
  const correct=`${word}を ください。`,options=optionSet(correct,[`${word}へ ください。`,`${word}が ください。`,`${word}で ください。`]);return{category:"Situasional",instruction:"Pilih ungkapan yang paling sesuai dengan situasi.",html:`Kamu ingin meminta “${meaning}” dengan sopan.`,options,answer:options.indexOf(correct),explanation:`Pola benda + をください digunakan untuk meminta sesuatu dengan sopan: ${correct}`,material:`Bab ${bab} · Komunikasi praktis`,srsId:`kanji:${word}`}})}
function buildSelectedQuestions(){
  if(mockPackage){const pack=mockTestPackages[mockPackage];questions=[...pack.questions];$("heroQuestionTotal").textContent=questions.length;$("heroPackage").textContent=pack.label;return}
  const curated=curatedBabPackages[rangeStart];
  if(curated){questions=[...curated.questions];$("heroQuestionTotal").textContent=questions.length;$("heroPackage").textContent=`Bab ${rangeStart}–${rangeStart+4}`;return}
  const vocabulary=vocabularyQuestions(),kanji=kanjiQuestions(),grammar=grammarQuestions(),sentence=contextualQuestions("sentence"),reading=contextualQuestions("reading"),audio=contextualQuestions("audio"),situational=contextualQuestions("situational");
  questions=[...vocabulary.slice(0,2),...kanji.slice(0,2),...grammar.slice(0,2),sentence[0],reading[0],audio[0],situational[0]];
  questions=questions.filter(Boolean);if(!questions.length)questions=[...defaultQuestions];$("heroQuestionTotal").textContent=questions.length;$("heroPackage").textContent=`Bab ${rangeStart}–${rangeStart+4}`;
}
function updatePackagePreview(){
  if(mockPackage){const pack=mockTestPackages[mockPackage];$("selectedTestName").textContent=pack.label;$("selectedRangeText").textContent="Paket soal siap pakai dengan format ujian resmi (4 bagian), untuk latihan mandiri.";$("heroExamType").textContent="Paket Siap Pakai";$("heroPackage").textContent=pack.label;return}
  const curated=curatedBabPackages[rangeStart];
  $("selectedTestName").textContent=`Ujian per 5 Bab · Bab ${rangeStart}–${rangeStart+4}`;$("selectedRangeText").textContent=curated?`Soal disusun manual dari kosakata, kanji, dan pola kalimat Bab ${rangeStart}–${rangeStart+4}.`:`Materi gabungan diambil dari Bab ${rangeStart}, ${rangeStart+1}, ${rangeStart+2}, ${rangeStart+3}, dan ${rangeStart+4}.`;$("heroExamType").textContent="Per 5 Bab";$("heroPackage").textContent=`Bab ${rangeStart}–${rangeStart+4}`}
function speak(text){if(!("speechSynthesis" in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="ja-JP";u.rate=.82;speechSynthesis.speak(u)}
function activeQuestionIndex(){return reviewOnly?reviewIndexes[current]:current}
function renderNavigator(){
  const grid=$("numberGrid");grid.replaceChildren();
  questions.forEach((_,index)=>{const b=document.createElement("button");b.textContent=index+1;b.classList.toggle("current",index===activeQuestionIndex());b.classList.toggle("answered",answers[index]!==null);b.classList.toggle("flagged",flags[index]);b.onclick=()=>{reviewOnly=false;current=index;renderQuestion()};grid.append(b)});
  $("answeredCount").textContent=`${answers.filter(v=>v!==null).length} / ${questions.length}`;$("temporaryScore").textContent=questions.filter((q,i)=>checked[i]&&answers[i]===q.answer).length;$("flaggedCount").textContent=flags.filter(Boolean).length;
}
function renderQuestion(){
  const index=activeQuestionIndex(),q=questions[index];
  $("categoryBadge").textContent=q.category.toUpperCase();$("questionCounter").textContent=reviewOnly?`Tinjauan ${current+1} dari ${reviewIndexes.length}`:`Soal ${index+1} dari ${questions.length}`;$("instruction").textContent=q.instruction;$("questionText").innerHTML=q.html;$("questionText").classList.toggle("hide-furigana",!furigana);$("testProgress").style.width=`${((reviewOnly?current:index)+1)/(reviewOnly?reviewIndexes.length:questions.length)*100}%`;
  $("audioButton").hidden=!q.audio;if(q.audio)$("audioButton").onclick=()=>speak(q.audio);
  const box=$("answers");box.replaceChildren();q.options.forEach((option,choice)=>{const b=document.createElement("button");b.innerHTML=`<b>${String.fromCharCode(65+choice)}</b><span></span>`;b.querySelector("span").textContent=option;b.classList.toggle("selected",answers[index]===choice);if(checked[index]||reviewOnly){b.disabled=true;b.classList.toggle("correct",choice===q.answer);b.classList.toggle("wrong",answers[index]===choice&&choice!==q.answer)}b.onclick=()=>{answers[index]=choice;renderQuestion()};box.append(b)});
  const showExplanation=(checked[index]&&mode==="practice")||reviewOnly;$("explanation").hidden=!showExplanation;if(showExplanation){const correct=answers[index]===q.answer;$("explanation").className=`explanation${correct?"":" wrong"}`;$("explanation").innerHTML=`<b>${correct?"Jawaban benar":"Belum tepat"}</b>${q.explanation}`}
  $("flagQuestion").classList.toggle("active",flags[index]);$("flagQuestion").textContent=flags[index]?"★ Ditandai":"☆ Tandai soal";$("previousQuestion").disabled=current===0;$("checkAnswer").hidden=reviewOnly||checked[index]||mode==="simulation";$("checkAnswer").textContent="Periksa jawaban";$("nextQuestion").hidden=reviewOnly||(!checked[index]&&mode==="practice");$("nextQuestion").textContent=index===questions.length-1?"Lihat hasil →":"Soal berikutnya →";
  if(mode==="simulation"&&!reviewOnly){$("checkAnswer").hidden=false;$("checkAnswer").textContent=index===questions.length-1?"Simpan & lihat hasil":"Simpan & berikutnya"}
  renderNavigator();
}
function checkOrAdvance(){
  const index=activeQuestionIndex();if(answers[index]===null){$("explanation").hidden=false;$("explanation").className="explanation wrong";$("explanation").innerHTML="<b>Pilih satu jawaban terlebih dahulu.</b>Setelah memilih, jawaban dapat diperiksa.";return}
  checked[index]=true;if(mode==="simulation"){if(index===questions.length-1)finishTest();else{current++;renderQuestion()}}else renderQuestion();
}
function advance(){if(activeQuestionIndex()===questions.length-1)finishTest();else{current++;renderQuestion()}}
function categoryScores(){const result={};questions.forEach((q,i)=>{result[q.category]??={correct:0,total:0};result[q.category].total++;if(answers[i]===q.answer)result[q.category].correct++});return result}
/* Kirim hasil ke Supabase (fire-and-forget, sama seperti srsPushItem di
   srs.js) supaya XP, status "quiz" di dashboard, dan panel Pantau Siswa
   ikut mencatat sesi ini. Gagal kirim (offline, dsb.) sengaja dibiarkan
   diam - tidak boleh mengganggu hasil yang sudah ditampilkan ke siswa. */
/* exam_type dikirim tetap "jlpt" (UI tidak lagi membedakan jenis ujian) -
   kolom quiz_results.exam_type masih dibatasi check (jlpt|jft) di DB. */
function submitQuizResult(correct,total,catScores){
  if(!window.supabaseClient)return;
  window.supabaseClient.auth.getUser().then(({data})=>{
    const uid=data&&data.user&&data.user.id;
    if(!uid)return;
    return window.supabaseClient.from("quiz_results").insert({user_id:uid,exam_type:"jlpt",correct_count:correct,total_count:total,category_scores:catScores});
  }).then((res)=>{if(res&&res.error)console.warn("submitQuizResult gagal:",res.error.message)}).catch(()=>{});
}
/* Jawaban benar/salah dikirim sebagai review SRS ke halaman utama (iframe
   ini tidak memuat srs.js sendiri, tapi window.parent yang menampung
   iframe ini sudah memuatnya - sama origin, aman diakses). Ini yang
   membuat kesalahan di quiz benar-benar terjadwal untuk diulang lewat
   SRS, bukan cuma tampil sekali di bank kesalahan lalu terlupakan. */
function pushQuizAnswersToSrs(){
  if(!window.parent||typeof window.parent.srsReview!=="function")return;
  questions.forEach((q,i)=>{
    if(!q.srsId)return;
    try{window.parent.srsReview(q.srsId,answers[i]===q.answer?"good":"again")}catch(e){}
  });
}
function finishTest(){
  clearInterval(timerId);checked=checked.map(()=>true);const correct=questions.filter((q,i)=>answers[i]===q.answer).length,score=Math.round(correct/questions.length*100);$("testScreen").hidden=true;$("resultScreen").hidden=false;$("finalScore").textContent=score;$("resultTitle").textContent=score>=80?"Fondasi kamu sudah kuat.":score>=60?"Fondasi sudah terbentuk.":"Mari perkuat dasar sedikit lagi.";$("resultSummary").textContent=`${correct} dari ${questions.length} soal benar. ${questions.length-correct} soal tersimpan dalam bank kesalahan untuk ditinjau kembali.`;
  submitQuizResult(correct,questions.length,categoryScores());
  pushQuizAnswersToSrs();
  const categoryBox=$("categoryResults");categoryBox.replaceChildren();Object.entries(categoryScores()).forEach(([name,value])=>{const pct=Math.round(value.correct/value.total*100),row=document.createElement("div");row.innerHTML=`<span>${name}</span><i style="--score:${pct}%"></i><b>${pct}%</b>`;categoryBox.append(row)});
  const weakest=Object.entries(categoryScores()).sort((a,b)=>a[1].correct/a[1].total-b[1].correct/b[1].total).slice(0,2);$("recommendations").innerHTML=weakest.map(([name])=>`<div><b>Perkuat ${name}</b>Ulangi materi dan latihan terkait sebelum mencoba simulasi berikutnya.</div>`).join("")+`<div><b>Ulangi bank kesalahan</b>Fokuskan sesi berikutnya pada ${questions.length-correct} soal yang masih salah.</div>`;
  reviewIndexes=questions.map((q,i)=>answers[i]!==q.answer?i:-1).filter(i=>i>=0);const list=$("mistakeList");list.replaceChildren();reviewIndexes.forEach(i=>{const q=questions[i],a=document.createElement("article");a.innerHTML=`<b>Soal ${i+1} · ${q.category}</b><p>Jawabanmu: ${answers[i]===null?"Belum dijawab":q.options[answers[i]]} · Jawaban benar: ${q.options[q.answer]}</p><p>${q.explanation}</p><small>Pelajari kembali: ${q.material}</small>`;list.append(a)});window.scrollTo({top:0,behavior:"smooth"});
}
function startTimer(){clearInterval(timerId);seconds=Math.max(720,questions.length*40);const m0=String(Math.floor(seconds/60)).padStart(2,"0"),s0=String(seconds%60).padStart(2,"0");$("timer").textContent=`${m0}:${s0}`;if(!$("timerEnabled").checked){$("timer").textContent="Tanpa timer";return}timerId=setInterval(()=>{seconds--;const m=String(Math.floor(seconds/60)).padStart(2,"0"),s=String(seconds%60).padStart(2,"0");$("timer").textContent=`${m}:${s}`;if(seconds<=0)finishTest()},1000)}
function startTest(){if(!questionBankReady)return;buildSelectedQuestions();current=0;answers=Array(questions.length).fill(null);checked=Array(questions.length).fill(false);flags=Array(questions.length).fill(false);reviewOnly=false;$("startScreen").hidden=true;$("resultScreen").hidden=true;$("testScreen").hidden=false;startTimer();renderQuestion();window.scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll("#sourceChoice button").forEach(button=>button.onclick=()=>{
  mockPackage=button.dataset.package||"";
  document.querySelectorAll("#sourceChoice button").forEach(item=>item.classList.toggle("active",item===button));
  $("chapterRange").disabled=!!mockPackage;
  $("chapterRangeBlock").classList.toggle("disabled",!!mockPackage);
  updatePackagePreview();
});
$("chapterRange").onchange=()=>{rangeStart=Number($("chapterRange").value);updatePackagePreview()};
document.querySelectorAll("#modeChoice button").forEach(b=>b.onclick=()=>{mode=b.dataset.mode;document.querySelectorAll("#modeChoice button").forEach(x=>x.classList.toggle("active",x===b))});
updatePackagePreview();
$("startTest").onclick=startTest;$("checkAnswer").onclick=checkOrAdvance;$("nextQuestion").onclick=advance;$("previousQuestion").onclick=()=>{if(current>0){current--;renderQuestion()}};$("flagQuestion").onclick=()=>{const i=activeQuestionIndex();flags[i]=!flags[i];renderQuestion()};$("furiganaToggle").onclick=()=>{furigana=!furigana;$("furiganaToggle").textContent=`振 Furigana: ${furigana?"aktif":"mati"}`;renderQuestion()};$("finishEarly").onclick=finishTest;$("restartTest").onclick=()=>{$("resultScreen").hidden=true;$("startScreen").hidden=false;window.scrollTo({top:0,behavior:"smooth"})};$("reviewMistakes").onclick=()=>{$("mistakeBank").hidden=false;$("mistakeBank").scrollIntoView({behavior:"smooth"})};$("closeMistakes").onclick=()=>{$("mistakeBank").hidden=true};
